-- 此sql已于2012-03-09 11:00运行
--删除粤A.AKP252的迁移记录
DELETE FROM BS_CAR_DRIVER_HISTORY 
  WHERE TO_CAR_ID=(SELECT C.ID FROM BS_CAR C WHERE CONCAT(PLATE_TYPE,'.',PLATE_NO)='粤A.AKP252');
--删除粤A.AC1964的交通违章
DELETE FROM BS_CASE_INFRACT_TRAFFIC 
  WHERE ID=(SELECT ID FROM BS_CASE_BASE WHERE CAR_ID=(SELECT C.ID FROM BS_CAR C WHERE CONCAT(PLATE_TYPE,'.',PLATE_NO)='粤A.AC1964'));
DELETE FROM BS_CASE_BASE 
  WHERE CAR_ID=(SELECT C.ID FROM BS_CAR C WHERE CONCAT(PLATE_TYPE,'.',PLATE_NO)='粤A.AC1964');
--删除粤A.AC1266的黑名单
DELETE FROM BS_BLACKLIST
  WHERE CAR_ID=(SELECT C.ID FROM BS_CAR C WHERE CONCAT(PLATE_TYPE,'.',PLATE_NO)='粤A.AC1266');

--删除迁移记录
DELETE FROM BS_CAR WHERE '粤A.0425'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.4564646'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.86042'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AA8521'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AB1797'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AB8489'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AB9787'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AC0517'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AC1266'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AC1762'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AC1964'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AC2297'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AC2297.'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AC3927'=CONCAT(PLATE_TYPE,'.',PLATE_NO);
DELETE FROM BS_CAR WHERE '粤A.AKP252'=CONCAT(PLATE_TYPE,'.',PLATE_NO);

