-- ##bcÆ½Ì¨µÄ oracle ½¨±í½Å±¾##

-- md5º¯Êý£ºselect md5('888888') from dual --> 21218cca77804d2ba1922c33e0151105
CREATE OR REPLACE FUNCTION md5(passwd IN VARCHAR2)
RETURN VARCHAR2 IS retval varchar2(32);
BEGIN
  retval := lower(utl_raw.cast_to_raw(DBMS_OBFUSCATION_TOOLKIT.MD5(INPUT_STRING => passwd)));
  RETURN retval;
END;
/

-- ´´½¨ÐòÁÐ£¬¿ªÊ¼ÓÚ1Ç§Íò£¬·½±ãÀúÊ·Êý¾ÝµÄ×ª»»
CREATE sequence HIBERNATE_SEQUENCE
    minvalue 1
    start with 10000000
    increment by 1
    cache 20;

-- ²âÊÔÓÃµÄ±í
CREATE TABLE BC_EXAMPLE (
    ID number(19) NOT NULL,
    NAME varchar2(255) NOT NULL,
    CODE varchar2(255),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_EXAMPLE IS '²âÊÔÓÃµÄ±í';
COMMENT ON COLUMN BC_EXAMPLE.NAME IS 'Ãû³Æ';

-- ÏµÍ³±êÊ¶Ïà¹ØÄ£¿é
-- ÏµÍ³×ÊÔ´
CREATE TABLE BC_IDENTITY_RESOURCE (
    ID number(19) NOT NULL,
    UID_ varchar2(36),
    TYPE_ number(1)  DEFAULT 0 NOT NULL,
    STATUS_ number(1)  DEFAULT 0 NOT NULL,
    INNER_ number(1)  DEFAULT 0 NOT NULL,
    BELONG number(19),
    ORDER_ varchar2(100),
    NAME varchar2(255) NOT NULL,
    URL varchar2(255),
    ICONCLASS varchar2(255),
    OPTION_ varchar2(4000),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_IDENTITY_RESOURCE IS 'ÏµÍ³×ÊÔ´';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.TYPE_ IS 'ÀàÐÍ£º1-ÎÄ¼þ¼Ð,2-ÄÚ²¿Á´½Ó,3-Íâ²¿Á´½Ó,4-html';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.STATUS_ IS '×´Ì¬£º0-ÆôÓÃÖÐ,1-ÒÑ½ûÓÃ,2-ÒÑÉ¾³ý';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.INNER_ IS 'ÊÇ·ñÎªÄÚÖÃ¶ÔÏó:0-·ñ,1-ÊÇ';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.BELONG IS 'ËùÁ¥ÊôµÄ×ÊÔ´';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.ORDER_ IS 'ÅÅÐòºÅ';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.NAME IS 'Ãû³Æ';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.URL IS 'µØÖ·';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.ICONCLASS IS 'Í¼±êÑùÊ½';
COMMENT ON COLUMN BC_IDENTITY_RESOURCE.OPTION_ IS 'À©Õ¹²ÎÊý';

-- ½ÇÉ«
CREATE TABLE BC_IDENTITY_ROLE (
    ID number(19) NOT NULL,
    CODE varchar2(100) NOT NULL,
    ORDER_ varchar2(100),
    NAME varchar2(255) NOT NULL,
    UID_ varchar2(36),
   	TYPE_ number(1)  NOT NULL,
    STATUS_ number(1)  NOT NULL,
    INNER_ number(1)  NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_IDENTITY_ROLE IS '½ÇÉ«';
COMMENT ON COLUMN BC_IDENTITY_ROLE.CODE IS '±àÂë';
COMMENT ON COLUMN BC_IDENTITY_ROLE.ORDER_ IS 'ÅÅÐòºÅ';
COMMENT ON COLUMN BC_IDENTITY_ROLE.NAME IS 'Ãû³Æ';
COMMENT ON COLUMN BC_IDENTITY_ROLE.TYPE_ IS 'ÀàÐÍ';
COMMENT ON COLUMN BC_IDENTITY_ROLE.STATUS_ IS '×´Ì¬£º0-ÆôÓÃÖÐ,1-ÒÑ½ûÓÃ,2-ÒÑÉ¾³ý';
COMMENT ON COLUMN BC_IDENTITY_ROLE.INNER_ IS 'ÊÇ·ñÎªÄÚÖÃ¶ÔÏó:0-·ñ,1-ÊÇ';

-- ½ÇÉ«Óë×ÊÔ´µÄ¹ØÁª
CREATE TABLE BC_IDENTITY_ROLE_RESOURCE (
    RID number(19) NOT NULL,
    SID number(19) NOT NULL,
    PRIMARY KEY (RID,SID)
);
COMMENT ON TABLE BC_IDENTITY_ROLE_RESOURCE IS '½ÇÉ«Óë×ÊÔ´µÄ¹ØÁª£º½ÇÉ«¿ÉÒÔ·ÃÎÊÄÄÐ©×ÊÔ´';
COMMENT ON COLUMN BC_IDENTITY_ROLE_RESOURCE.RID IS '½ÇÉ«ID';
COMMENT ON COLUMN BC_IDENTITY_ROLE_RESOURCE.SID IS '×ÊÔ´ID';
ALTER TABLE BC_IDENTITY_ROLE_RESOURCE ADD CONSTRAINT BCFK_RS_ROLE FOREIGN KEY (RID) REFERENCES BC_IDENTITY_ROLE (ID);
ALTER TABLE BC_IDENTITY_ROLE_RESOURCE ADD CONSTRAINT BCFK_RS_RESOURCE FOREIGN KEY (SID) REFERENCES BC_IDENTITY_RESOURCE (ID);

-- Ö°Îñ
CREATE TABLE BC_IDENTITY_DUTY (
    ID int NOT NULL,
    CODE varchar2(100) NOT NULL,
    NAME varchar2(255) NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_IDENTITY_DUTY IS 'Ö°Îñ';
COMMENT ON COLUMN BC_IDENTITY_DUTY.CODE IS '±àÂë';
COMMENT ON COLUMN BC_IDENTITY_DUTY.NAME IS 'Ãû³Æ';

-- ²ÎÓëÕßµÄÀ©Õ¹ÊôÐÔ
CREATE TABLE BC_IDENTITY_ACTOR_DETAIL (
    ID number(19) NOT NULL,
    CREATE_DATE date,
    WORK_DATE date,
    ISO number(1)  default 0,
    SEX number(1)  default 0,
   	CARD varchar2(20),
    DUTY_ID number(19),
   	COMMENT_ varchar2(4000),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_IDENTITY_ACTOR_DETAIL IS '²ÎÓëÕßµÄÀ©Õ¹ÊôÐÔ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_DETAIL.CREATE_DATE IS '´´½¨Ê±¼ä';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_DETAIL.WORK_DATE IS 'user-ÈëÖ°Ê±¼ä';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_DETAIL.SEX IS 'user-ÐÔ±ð£º0-Î´ÉèÖÃ,1-ÄÐ,2-Å®';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_DETAIL.DUTY_ID IS 'user-Ö°ÎñID';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_DETAIL.COMMENT_ IS '±¸×¢';
ALTER TABLE BC_IDENTITY_ACTOR_DETAIL ADD CONSTRAINT BCFK_ACTORDETAIL_DUTY FOREIGN KEY (DUTY_ID) REFERENCES BC_IDENTITY_DUTY (ID);

-- ²ÎÓëÕß
CREATE TABLE BC_IDENTITY_ACTOR (
    ID number(19) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    TYPE_ number(1)  DEFAULT 0 NOT NULL,
    STATUS_ number(1)  DEFAULT 0 NOT NULL,
    INNER_ number(1)  DEFAULT 0 NOT NULL,
    CODE varchar2(100) NOT NULL,
    NAME varchar2(255) NOT NULL,
    PY varchar2(255),
    ORDER_ varchar2(100),
    EMAIL varchar2(255),
    PHONE varchar2(255),
    DETAIL_ID number(19),
    PRIMARY KEY (ID)
);
ALTER TABLE BC_IDENTITY_ACTOR ADD CONSTRAINT BCFK_ACTOR_ACTORDETAIL FOREIGN KEY (DETAIL_ID) 
	REFERENCES BC_IDENTITY_ACTOR_DETAIL (ID) ON DELETE CASCADE;
CREATE INDEX BCIDX_ACTOR_TYPE ON BC_IDENTITY_ACTOR (TYPE_ ASC);
COMMENT ON TABLE BC_IDENTITY_ACTOR IS '²ÎÓëÕß(´ú±íÒ»¸öÈË»ò×éÖ¯£¬×éÖ¯Ò²¿ÉÒÔÊÇµ¥Î»¡¢²¿ÃÅ¡¢¸ÚÎ»¡¢ÍÅ¶ÓµÈ)';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.UID_ IS 'È«¾Ö±êÊ¶';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.TYPE_ IS 'ÀàÐÍ£º0-Î´¶¨Òå,1-µ¥Î»,2-²¿ÃÅ,3-¸ÚÎ»,4-ÓÃ»§';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.STATUS_ IS '×´Ì¬£º0-ÆôÓÃÖÐ,1-ÒÑ½ûÓÃ,2-ÒÑÉ¾³ý';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.INNER_ IS 'ÊÇ·ñÎªÄÚÖÃ¶ÔÏó:0-·ñ,1-ÊÇ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.CODE IS '±àÂë';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.NAME IS 'Ãû³Æ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.PY IS 'Ãû³ÆµÄÆ´Òô';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.ORDER_ IS 'Í¬Àà²ÎÓëÕßÖ®¼äµÄÅÅÐòºÅ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.EMAIL IS 'ÓÊÏä';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.PHONE IS 'ÁªÏµµç»°';
COMMENT ON COLUMN BC_IDENTITY_ACTOR.DETAIL_ID IS 'À©Õ¹±íµÄID';

-- ²ÎÓëÕßÖ®¼äµÄ¹ØÁª¹ØÏµ
CREATE TABLE BC_IDENTITY_ACTOR_RELATION (
    TYPE_ number(2) NOT NULL,
    MASTER_ID number(19) NOT NULL,
   	FOLLOWER_ID number(19) NOT NULL,
    ORDER_ varchar2(100),
    PRIMARY KEY (MASTER_ID,FOLLOWER_ID,TYPE_)
);
COMMENT ON TABLE BC_IDENTITY_ACTOR_RELATION IS '²ÎÓëÕßÖ®¼äµÄ¹ØÁª¹ØÏµ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_RELATION.TYPE_ IS '¹ØÁªÀàÐÍ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_RELATION.MASTER_ID IS 'Ö÷¿Ø·½ID';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_RELATION.FOLLOWER_ID IS '´ÓÊô·½ID';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_RELATION.ORDER_ IS '´ÓÊô·½Ö®¼äµÄÅÅÐòºÅ';
ALTER TABLE BC_IDENTITY_ACTOR_RELATION ADD CONSTRAINT BCFK_AR_MASTER FOREIGN KEY (MASTER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_IDENTITY_ACTOR_RELATION ADD CONSTRAINT BCFK_AR_FOLLOWER FOREIGN KEY (FOLLOWER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
CREATE INDEX BCIDX_AR_TM ON BC_IDENTITY_ACTOR_RELATION (TYPE_, MASTER_ID);
CREATE INDEX BCIDX_AR_TF ON BC_IDENTITY_ACTOR_RELATION (TYPE_, FOLLOWER_ID);

-- ACTORÁ¥ÊôÐÅÏ¢µÄ±ä¶¯ÀúÊ·
CREATE TABLE BC_IDENTITY_ACTOR_HISTORY (
   ID                   NUMBER(19)           NOT NULL,
   CREATE_DATE          DATE                 NOT NULL,
   START_DATE           DATE,
   END_DATE             DATE,
   ACTOR_TYPE           NUMBER(1)            NOT NULL,
   ACTOR_ID             NUMBER(19)           NOT NULL,
   ACTOR_NAME           VARCHAR2(100)        NOT NULL,
   UPPER_ID             NUMBER(19),
   UPPER_NAME           VARCHAR2(255),
   UNIT_ID              NUMBER(19),
   UNIT_NAME            VARCHAR2(255),
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_IDENTITY_ACTOR_HISTORY IS 'ACTORÁ¥ÊôÐÅÏ¢µÄ±ä¶¯ÀúÊ·';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.CREATE_DATE IS '´´½¨Ê±¼ä';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.START_DATE IS 'ÆðÊ¼Ê±¶Î';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.END_DATE IS '½áÊøÊ±¶Î';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.ACTOR_TYPE IS 'ACTORÀàÐÍ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.ACTOR_ID IS 'ACTORID';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.ACTOR_NAME IS 'ACTORÃû³Æ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.UPPER_ID IS 'ËùÊôÉÏ¼¶ID';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.UPPER_NAME IS 'ËùÊôÉÏ¼¶Ãû³Æ';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.UNIT_ID IS 'ËùÔÚµ¥Î»ID';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.UNIT_NAME IS 'ËùÔÚµ¥Î»Ãû³Æ';
ALTER TABLE BC_IDENTITY_ACTOR_HISTORY ADD CONSTRAINT BCFK_ACTORHISTORY_ACTOR FOREIGN KEY (ACTOR_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
CREATE INDEX BCIDX_ACTORHISTORY_UPPERID ON BC_IDENTITY_ACTOR_HISTORY (UPPER_ID ASC);
CREATE INDEX BCIDX_ACTORHISTORY_UNITID ON BC_IDENTITY_ACTOR_HISTORY (UNIT_ID ASC);
-- CREATE INDEX BCIDX_ACTORHISTORY_ACTORID ON BC_IDENTITY_ACTOR_HISTORY (ACTOR_ID ASC);

-- ÈÏÖ¤ÐÅÏ¢
CREATE TABLE BC_IDENTITY_AUTH (
    ID  number(19) NOT NULL,
    PASSWORD varchar2(32) NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_IDENTITY_AUTH IS 'ÈÏÖ¤ÐÅÏ¢';
COMMENT ON COLUMN BC_IDENTITY_AUTH.ID IS 'ÓëActor±íµÄid¶ÔÓ¦';
COMMENT ON COLUMN BC_IDENTITY_AUTH.PASSWORD IS '¾­MD5¼ÓÃÜµÄÃÜÂë';
ALTER TABLE BC_IDENTITY_AUTH ADD CONSTRAINT BCFK_AUTH_ACTOR FOREIGN KEY (ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);

-- ±êÊ¶Éú³ÉÆ÷
CREATE TABLE BC_IDENTITY_IDGENERATOR (
  TYPE_ varchar2(45) NOT NULL,
  VALUE_ number(19) NOT NULL,
  FORMAT varchar2(45) ,
  PRIMARY KEY (TYPE_)
);
COMMENT ON TABLE BC_IDENTITY_IDGENERATOR IS '±êÊ¶Éú³ÉÆ÷,ÓÃÓÚÉú³ÉÖ÷¼ü»òÎ¨Ò»±àÂëÓÃ';
COMMENT ON COLUMN BC_IDENTITY_IDGENERATOR.TYPE_ IS '·ÖÀà';
COMMENT ON COLUMN BC_IDENTITY_IDGENERATOR.VALUE_ IS 'µ±Ç°Öµ';
COMMENT ON COLUMN BC_IDENTITY_IDGENERATOR.FORMAT IS '¸ñÊ½Ä£°å,Èç¡°case-${V}¡±¡¢¡°${T}-${V}¡±,V´ú±ívalueµÄÖµ£¬T´ú±ítype_µÄÖµ';

-- ²ÎÓëÕßÓë½ÇÉ«µÄ¹ØÁª
CREATE TABLE BC_IDENTITY_ROLE_ACTOR (
    AID number(19) NOT NULL,
    RID number(19) NOT NULL,
    PRIMARY KEY (AID,RID)
);
ALTER TABLE BC_IDENTITY_ROLE_ACTOR ADD CONSTRAINT BCFK_RA_ACTOR FOREIGN KEY (AID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_IDENTITY_ROLE_ACTOR ADD CONSTRAINT BCFK_RA_ROLE FOREIGN KEY (RID) 
	REFERENCES BC_IDENTITY_ROLE (ID);
COMMENT ON TABLE BC_IDENTITY_ROLE_ACTOR IS '²ÎÓëÕßÓë½ÇÉ«µÄ¹ØÁª£º²ÎÓëÕßÓµÓÐÄÄÐ©½ÇÉ«';
COMMENT ON COLUMN BC_IDENTITY_ROLE_ACTOR.AID IS '²ÎÓëÕßID';
COMMENT ON COLUMN BC_IDENTITY_ROLE_ACTOR.RID IS '½ÇÉ«ID';
	
-- ##ÏµÍ³×ÀÃæÏà¹ØÄ£¿é##
-- ×ÀÃæ¿ì½Ý·½Ê½
create table BC_DESKTOP_SHORTCUT (
    ID number(19) NOT NULL,
    UID_ varchar(36),
    STATUS_ number(1) NOT NULL,
    INNER_ number(1) NOT NULL,
    ORDER_ varchar(100) NOT NULL,
    STANDALONE number(1) NOT NULL,
    NAME varchar(255),
    URL varchar(255),
    ICONCLASS varchar(255),
    SID number(19),
    AID number(19),
    primary key (ID)
);
COMMENT ON TABLE BC_DESKTOP_SHORTCUT IS '×ÀÃæ¿ì½Ý·½Ê½';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.UID_ IS 'È«¾Ö±êÊ¶';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.STATUS_ IS '×´Ì¬£º0-ÆôÓÃÖÐ,1-ÒÑ½ûÓÃ,2-ÒÑÉ¾³ý';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.INNER_ IS 'ÊÇ·ñÎªÄÚÖÃ¶ÔÏó:0-·ñ,1-ÊÇ';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.STANDALONE IS 'ÊÇ·ñÔÚ¶ÀÁ¢µÄä¯ÀÀÆ÷´°¿ÚÖÐ´ò¿ª';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.NAME IS 'Ãû³Æ,Îª¿ÕÔòÊ¹ÓÃÄ£¿éµÄÃû³Æ';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.URL IS 'µØÖ·,Îª¿ÕÔòÊ¹ÓÃÄ£¿éµÄµØÖ·';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.ICONCLASS IS 'Í¼±êÑùÊ½';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.SID IS '¶ÔÓ¦µÄ×ÊÔ´ID';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.AID IS 'ËùÊôµÄ²ÎÓëÕß(Èç¹ûÎªÉÏ¼¶²ÎÓëÕß,Èçµ¥Î»²¿ÃÅ,ÔòÆäÏÂµÄËùÓÐ²ÎÓëÕß¶¼ÓµÓÐ¸Ã¿ì½Ý·½Ê½)';
ALTER TABLE BC_DESKTOP_SHORTCUT ADD CONSTRAINT BCFK_SHORTCUT_RESOURCE FOREIGN KEY (SID) 
	REFERENCES BC_IDENTITY_RESOURCE (ID);
ALTER TABLE BC_DESKTOP_SHORTCUT ADD CONSTRAINT BCFK_SHORTCUT_ACTOR FOREIGN KEY (AID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);

-- ¸öÈËÉèÖÃ
CREATE TABLE BC_DESKTOP_PERSONAL (
    ID number(19) NOT NULL,
    UID_ varchar2(36),
    STATUS_ number(1)  NOT NULL,
    FONT varchar2(2) NOT NULL,
    THEME varchar2(255) NOT NULL,
    AID number(19),
    INNER_ number(1)  NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_DESKTOP_PERSONAL IS '¸öÈËÉèÖÃ';
COMMENT ON COLUMN BC_DESKTOP_PERSONAL.UID_ IS 'È«¾Ö±êÊ¶';
COMMENT ON COLUMN BC_DESKTOP_PERSONAL.STATUS_ IS '×´Ì¬£º0-ÆôÓÃÖÐ,1-ÒÑ½ûÓÃ,2-ÒÑÉ¾³ý';
COMMENT ON COLUMN BC_DESKTOP_PERSONAL.FONT IS '×ÖÌå´óÐ¡£¬Èç12¡¢14¡¢16';
COMMENT ON COLUMN BC_DESKTOP_PERSONAL.THEME IS 'Ö÷ÌâÃû³Æ,Èçbase';
COMMENT ON COLUMN BC_DESKTOP_PERSONAL.AID IS 'ËùÊôµÄ²ÎÓëÕß';
COMMENT ON COLUMN BC_DESKTOP_PERSONAL.INNER_ IS 'ÊÇ·ñÎªÄÚÖÃ¶ÔÏó:0-·ñ,1-ÊÇ';
ALTER TABLE BC_DESKTOP_PERSONAL ADD CONSTRAINT BCFK_PERSONAL_ACTOR FOREIGN KEY (AID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_DESKTOP_PERSONAL ADD CONSTRAINT BCUK_PERSONAL_AID UNIQUE (AID);


-- ÏûÏ¢Ä£¿é
CREATE TABLE BC_MESSAGE (
    ID number(19) NOT NULL,
    UID_ varchar2(36),
    STATUS_ number(1) default 0 NOT NULL,
    TYPE_ number(1) default 0 NOT NULL,
    SENDER_ID number(19) NOT NULL,
    SEND_DATE date NOT NULL,
    RECEIVER_ID number(19) NOT NULL,
    READ_ number(1) default 0 NOT NULL,
    FROM_ID number(19),
    FROM_TYPE number(19),
    SUBJECT varchar2(255) NOT NULL,
    CONTENT varchar2(4000),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_MESSAGE IS 'ÏûÏ¢Ä£¿é';
COMMENT ON COLUMN BC_MESSAGE.STATUS_ IS '×´Ì¬£º0-·¢ËÍÖÐ,1-ÒÑ·¢ËÍ,2-ÒÑÉ¾³ý,3-·¢ËÍÊ§°Ü';
COMMENT ON COLUMN BC_MESSAGE.TYPE_ IS 'ÏûÏ¢ÀàÐÍ';
COMMENT ON COLUMN BC_MESSAGE.SENDER_ID IS '·¢ËÍÕß';
COMMENT ON COLUMN BC_MESSAGE.SEND_DATE IS '·¢ËÍÊ±¼ä';
COMMENT ON COLUMN BC_MESSAGE.RECEIVER_ID IS '½ÓÊÕÕß';
COMMENT ON COLUMN BC_MESSAGE.FROM_ID IS 'À´Ô´±êÊ¶';
COMMENT ON COLUMN BC_MESSAGE.FROM_TYPE IS 'À´Ô´ÀàÐÍ';
COMMENT ON COLUMN BC_MESSAGE.READ_ IS 'ÒÑÔÄ±ê¼Ç';
COMMENT ON COLUMN BC_MESSAGE.SUBJECT IS '±êÌâ';
COMMENT ON COLUMN BC_MESSAGE.CONTENT IS 'ÄÚÈÝ';
ALTER TABLE BC_MESSAGE ADD CONSTRAINT BCFK_MESSAGE_SENDER FOREIGN KEY (SENDER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BC_MESSAGE ADD CONSTRAINT BCFK_MESSAGE_REVEIVER FOREIGN KEY (RECEIVER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
CREATE INDEX BCIDX_MESSAGE_FROMID ON BC_MESSAGE (FROM_TYPE,FROM_ID);
CREATE INDEX BCIDX_MESSAGE_TYPE ON BC_MESSAGE (TYPE_);

-- ¹¤×÷ÊÂÏî
CREATE TABLE BC_WORK (
    ID number(19) NOT NULL,
    CLASSIFIER varchar2(500) NOT NULL,
    SUBJECT varchar2(255) NOT NULL,
    FROM_ID number(19),
    FROM_TYPE number(19),
    FROM_INFO varchar2(255),
    OPEN_URL varchar2(255),
    CONTENT varchar2(4000),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_WORK IS '¹¤×÷ÊÂÏî';
COMMENT ON COLUMN BC_WORK.CLASSIFIER IS '·ÖÀà´Ê,¿É¶à¼¶·ÖÀà,¼¶¼äÊ¹ÓÃ/Á¬½Ó,Èç¡°·¢ÎÄÀà/ÕýÊ½·¢ÎÄ¡±';
COMMENT ON COLUMN BC_WORK.SUBJECT IS '±êÌâ';
COMMENT ON COLUMN BC_WORK.FROM_ID IS 'À´Ô´±êÊ¶';
COMMENT ON COLUMN BC_WORK.FROM_TYPE IS 'À´Ô´ÀàÐÍ';
COMMENT ON COLUMN BC_WORK.FROM_INFO IS 'À´Ô´ÃèÊö';
COMMENT ON COLUMN BC_WORK.OPEN_URL IS '´ò¿ªµÄUrlÄ£°å';
COMMENT ON COLUMN BC_WORK.CONTENT IS 'ÄÚÈÝ';
CREATE INDEX BCIDX_WORK_FROM ON BC_WORK (FROM_TYPE,FROM_ID);

-- ´ý°ìÊÂÏî
CREATE TABLE BC_WORK_TODO (
    ID number(19) NOT NULL,
    WORK_ID number(19) NOT NULL,
    SENDER_ID number(19) NOT NULL,
    SEND_DATE date NOT NULL,
    WORKER_ID number(19) NOT NULL,
    INFO varchar2(255),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_WORK_TODO IS '´ý°ìÊÂÏî';
COMMENT ON COLUMN BC_WORK_TODO.WORK_ID IS '¹¤×÷ÊÂÏîID';
COMMENT ON COLUMN BC_WORK_TODO.SENDER_ID IS '·¢ËÍÕß';
COMMENT ON COLUMN BC_WORK_TODO.SEND_DATE IS '·¢ËÍÊ±¼ä';
COMMENT ON COLUMN BC_WORK_TODO.WORKER_ID IS '·¢ËÍÕß';
COMMENT ON COLUMN BC_WORK_TODO.INFO IS '¸½¼ÓËµÃ÷';
ALTER TABLE BC_WORK_TODO ADD CONSTRAINT BCFK_TODOWORK_WORK FOREIGN KEY (WORK_ID) 
	REFERENCES BC_WORK (ID);
ALTER TABLE BC_WORK_TODO ADD CONSTRAINT BCFK_TODOWORK_SENDER FOREIGN KEY (SENDER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_WORK_TODO ADD CONSTRAINT BCFK_TODOWORK_WORKER FOREIGN KEY (WORKER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);

-- ÒÑ°ìÊÂÏî
CREATE TABLE BC_WORK_DONE (
    ID number(19) NOT NULL,
    FINISH_DATE date NOT NULL,
    FINISH_YEAR number(4)  NOT NULL,
    FINISH_MONTH number(2)  NOT NULL,
    FINISH_DAY number(2)  NOT NULL,
    WORK_ID number(19) NOT NULL,
    SENDER_ID number(19) NOT NULL,
    SEND_DATE date NOT NULL,
    WORKER_ID number(19) NOT NULL,
    INFO varchar2(255),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_WORK_DONE IS 'ÒÑ°ìÊÂÏî';
COMMENT ON COLUMN BC_WORK_DONE.FINISH_DATE IS 'Íê³ÉÊ±¼ä';
COMMENT ON COLUMN BC_WORK_DONE.FINISH_YEAR IS 'Íê³ÉÊ±¼äµÄÄê¶È';
COMMENT ON COLUMN BC_WORK_DONE.FINISH_MONTH IS 'Íê³ÉÊ±¼äµÄÔÂ·Ý(1-12)';
COMMENT ON COLUMN BC_WORK_DONE.FINISH_DAY IS 'Íê³ÉÊ±¼äµÄÈÕ(1-31)';
COMMENT ON COLUMN BC_WORK_DONE.WORK_ID IS '¹¤×÷ÊÂÏîID';
COMMENT ON COLUMN BC_WORK_DONE.SENDER_ID IS '·¢ËÍÕß';
COMMENT ON COLUMN BC_WORK_DONE.SEND_DATE IS '·¢ËÍÊ±¼ä';
COMMENT ON COLUMN BC_WORK_DONE.WORKER_ID IS '·¢ËÍÕß';
COMMENT ON COLUMN BC_WORK_DONE.INFO IS '¸½¼ÓËµÃ÷';
ALTER TABLE BC_WORK_DONE ADD CONSTRAINT BCFK_DONEWORK_WORK FOREIGN KEY (WORK_ID) 
	REFERENCES BC_WORK (ID);
ALTER TABLE BC_WORK_DONE ADD CONSTRAINT BCFK_DONEWORK_SENDER FOREIGN KEY (SENDER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_WORK_DONE ADD CONSTRAINT BCFK_DONEWORK_WORKER FOREIGN KEY (WORKER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
CREATE INDEX BCIDX_DONEWORK_FINISHDATE ON BC_WORK_DONE (FINISH_YEAR,FINISH_MONTH,FINISH_DAY);


-- ÏµÍ³ÈÕÖ¾
CREATE TABLE BC_LOG_SYSTEM (
    ID number(19) NOT NULL,
    TYPE_ number(1)  NOT NULL,
    SUBJECT varchar2(500) NOT NULL,
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    C_IP varchar2(100),
    C_NAME varchar2(100),
    C_INFO varchar2(1000),
    S_IP varchar2(100),
    S_NAME varchar2(100),
    S_INFO varchar2(1000),
    CONTENT varchar2(4000),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_LOG_SYSTEM IS 'ÏµÍ³ÈÕÖ¾';
COMMENT ON COLUMN BC_LOG_SYSTEM.TYPE_ IS 'Àà±ð£º0-µÇÂ¼,1-×¢Ïú,2-³¬Ê±';
COMMENT ON COLUMN BC_LOG_SYSTEM.FILE_DATE IS '´´½¨Ê±¼ä';
COMMENT ON COLUMN BC_LOG_SYSTEM.SUBJECT IS '±êÌâ';
COMMENT ON COLUMN BC_LOG_SYSTEM.AUTHOR_ID IS '´´½¨ÈËID';
COMMENT ON COLUMN BC_LOG_SYSTEM.C_IP IS 'ÓÃ»§»úÆ÷IP';
COMMENT ON COLUMN BC_LOG_SYSTEM.C_NAME IS 'ÓÃ»§»úÆ÷Ãû³Æ';
COMMENT ON COLUMN BC_LOG_SYSTEM.C_INFO IS 'ÓÃ»§ä¯ÀÀÆ÷ÐÅÏ¢£ºUser-Agent';
COMMENT ON COLUMN BC_LOG_SYSTEM.S_IP IS '·þÎñÆ÷IP';
COMMENT ON COLUMN BC_LOG_SYSTEM.S_NAME IS '·þÎñÆ÷Ãû³Æ';
COMMENT ON COLUMN BC_LOG_SYSTEM.S_INFO IS '·þÎñÆ÷ÐÅÏ¢';
COMMENT ON COLUMN BC_LOG_SYSTEM.CONTENT IS 'ÏêÏ¸ÄÚÈÝ';
ALTER TABLE BC_LOG_SYSTEM ADD CONSTRAINT BCFK_SYSLOG_USER FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
CREATE INDEX BCIDX_SYSLOG_CLIENT ON BC_LOG_SYSTEM (C_IP);
CREATE INDEX BCIDX_SYSLOG_SERVER ON BC_LOG_SYSTEM (S_IP);


-- ¹«¸æÄ£¿é
CREATE TABLE BC_BULLETIN (
    ID number(19) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    UNIT_ID number(19),
    SCOPE number(1)  NOT NULL,
    STATUS_ number(1)  NOT NULL,
    OVERDUE_DATE date,
   	ISSUE_DATE date,
    ISSUER_ID number(19),
    SUBJECT varchar2(500) NOT NULL,
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19),
    MODIFIED_DATE date,
    CONTENT varchar2(4000) NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_BULLETIN IS '¹«¸æÄ£¿é';
COMMENT ON COLUMN BC_BULLETIN.UID_ IS '¹ØÁª¸½¼þµÄ±êÊ¶ºÅ';
COMMENT ON COLUMN BC_BULLETIN.UNIT_ID IS '¹«¸æËùÊôµ¥Î»ID';
COMMENT ON COLUMN BC_BULLETIN.SCOPE IS '¹«¸æ·¢²¼·¶Î§£º0-±¾µ¥Î»,1-È«ÏµÍ³';
COMMENT ON COLUMN BC_BULLETIN.STATUS_ IS '×´Ì¬:0-²Ý¸å,1-ÒÑ·¢²¼,2-ÒÑ¹ýÆÚ';
COMMENT ON COLUMN BC_BULLETIN.OVERDUE_DATE IS '¹ýÆÚÈÕÆÚ£ºÎª¿Õ´ú±íÓÀ²»¹ýÆÚ';
COMMENT ON COLUMN BC_BULLETIN.ISSUE_DATE IS '·¢²¼Ê±¼ä';
COMMENT ON COLUMN BC_BULLETIN.ISSUER_ID IS '·¢²¼ÈËID';
COMMENT ON COLUMN BC_BULLETIN.SUBJECT IS '±êÌâ';
COMMENT ON COLUMN BC_BULLETIN.FILE_DATE IS '´´½¨Ê±¼ä';
COMMENT ON COLUMN BC_BULLETIN.AUTHOR_ID IS '´´½¨ÈËID';
COMMENT ON COLUMN BC_BULLETIN.MODIFIER_ID IS '×îºóÐÞ¸ÄÈËID';
COMMENT ON COLUMN BC_BULLETIN.MODIFIED_DATE IS '×îºóÐÞ¸ÄÊ±¼ä';
COMMENT ON COLUMN BC_BULLETIN.CONTENT IS 'ÏêÏ¸ÄÚÈÝ';
ALTER TABLE BC_BULLETIN ADD CONSTRAINT BCFK_BULLETIN_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BC_BULLETIN ADD CONSTRAINT BCFK_BULLETIN_ISSUER FOREIGN KEY (ISSUER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BC_BULLETIN ADD CONSTRAINT BCFK_BULLETIN_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BC_BULLETIN ADD CONSTRAINT BCFK_BULLETIN_UNIT FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
CREATE INDEX BCIDX_BULLETIN_SEARCH ON BC_BULLETIN (SCOPE,UNIT_ID,STATUS_);

-- ÎÄµµ¸½¼þ
CREATE TABLE BC_DOCS_ATTACH (
    ID number(19) NOT NULL,
    STATUS_ number(1)  NOT NULL,
    PTYPE varchar2(36) NOT NULL,
    PUID varchar2(36) NOT NULL,
    SIZE_ number(19) NOT NULL,
    COUNT_ number(19) default 0 NOT NULL,
    EXT varchar2(10),
    APPPATH number(1)  NOT NULL,
    SUBJECT varchar2(500) NOT NULL,
    PATH varchar2(500) NOT NULL,
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19),
    MODIFIED_DATE date,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_DOCS_ATTACH IS 'ÎÄµµ¸½¼þ,¼ÇÂ¼ÎÄµµÓëÆäÏà¹Ø¸½¼þÖ®¼äµÄ¹ØÏµ';
COMMENT ON COLUMN BC_DOCS_ATTACH.STATUS_ IS '×´Ì¬£º0-ÆôÓÃÖÐ,1-ÒÑ½ûÓÃ,2-ÒÑÉ¾³ý';
COMMENT ON COLUMN BC_DOCS_ATTACH.PTYPE IS 'Ëù¹ØÁªÎÄµµµÄÀàÐÍ';
COMMENT ON COLUMN BC_DOCS_ATTACH.PUID IS 'Ëù¹ØÁªÎÄµµµÄUID';
COMMENT ON COLUMN BC_DOCS_ATTACH.SIZE_ IS 'ÎÄ¼þµÄ´óÐ¡(µ¥Î»Îª×Ö½Ú)';
COMMENT ON COLUMN BC_DOCS_ATTACH.COUNT_ IS 'ÎÄ¼þµÄÏÂÔØ´ÎÊý';
COMMENT ON COLUMN BC_DOCS_ATTACH.EXT IS 'ÎÄ¼þÀ©Õ¹Ãû£ºÈçpng¡¢doc¡¢mp3µÈ';
COMMENT ON COLUMN BC_DOCS_ATTACH.APPPATH IS 'Ö¸¶¨pathµÄÖµÊÇÏà¶ÔÓÚÓ¦ÓÃ²¿ÊðÄ¿Â¼ÏÂÂ·¾¶»¹ÊÇÏà¶ÔÓÚÈ«¾ÖÅäÖÃµÄapp.dataÄ¿Â¼ÏÂµÄÂ·¾¶';
COMMENT ON COLUMN BC_DOCS_ATTACH.SUBJECT IS 'ÎÄ¼þÃû³Æ(²»´øÂ·¾¶µÄ²¿·Ö)';
COMMENT ON COLUMN BC_DOCS_ATTACH.PATH IS 'ÎïÀíÎÄ¼þ±£´æµÄÏà¶ÔÂ·¾¶(Ïà¶ÔÓÚÈ«¾ÖÅäÖÃµÄ¸½¼þ¸ùÄ¿Â¼ÏÂµÄ×ÓÂ·¾¶£¬Èç"2011/bulletin/xxxx.doc")';

COMMENT ON COLUMN BC_DOCS_ATTACH.FILE_DATE IS '´´½¨Ê±¼ä';
COMMENT ON COLUMN BC_DOCS_ATTACH.AUTHOR_ID IS '´´½¨ÈËID';
COMMENT ON COLUMN BC_DOCS_ATTACH.MODIFIER_ID IS '×îºóÐÞ¸ÄÈËID';
COMMENT ON COLUMN BC_DOCS_ATTACH.MODIFIED_DATE IS '×îºóÐÞ¸ÄÊ±¼ä';
ALTER TABLE BC_DOCS_ATTACH ADD CONSTRAINT BCFK_ATTACH_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BC_DOCS_ATTACH ADD CONSTRAINT BCFK_ATTACH_MODIFIER FOREIGN KEY (MODIFIER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
CREATE INDEX BCIDX_ATTACH_PUID ON BC_DOCS_ATTACH (PUID);
CREATE INDEX BCIDX_ATTACH_PTYPE ON BC_DOCS_ATTACH (PTYPE);

-- ¸½¼þ´¦ÀíºÛ¼£
CREATE TABLE BC_DOCS_ATTACH_HISTORY (
    ID number(19) NOT NULL,
    AID number(19) NOT NULL,
    TYPE_ number(19) NOT NULL,
    SUBJECT varchar2(500) NOT NULL,
    FORMAT varchar2(10),
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19),
    MODIFIED_DATE date,
    C_IP varchar2(100),
    C_INFO varchar2(1000),
    MEMO varchar2(2000),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_DOCS_ATTACH_HISTORY IS '¸½¼þ´¦ÀíºÛ¼£';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.AID IS '¸½¼þID';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.TYPE_ IS '´¦ÀíÀàÐÍ£º0-ÏÂÔØ,1-ÔÚÏß²é¿´,2-¸ñÊ½×ª»»';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.SUBJECT IS '¼òµ¥ËµÃ÷';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.FORMAT IS 'ÏÂÔØµÄÎÄ¼þ¸ñÊ½»ò×ª»»ºóµÄÎÄ¼þ¸ñÊ½£ºÈçpdf¡¢doc¡¢mp3µÈ';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.C_IP IS '¿Í»§¶ËIP';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.C_INFO IS 'ä¯ÀÀÆ÷ÐÅÏ¢£ºUser-Agent';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.MEMO IS '±¸×¢';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.FILE_DATE IS '´¦ÀíÊ±¼ä';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.AUTHOR_ID IS '´´½¨ÈËID';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.MODIFIER_ID IS '×îºóÐÞ¸ÄÈËID';
COMMENT ON COLUMN BC_DOCS_ATTACH_HISTORY.MODIFIED_DATE IS '×îºóÐÞ¸ÄÊ±¼ä';
ALTER TABLE BC_DOCS_ATTACH_HISTORY ADD CONSTRAINT BCFK_ATTACHHISTORY_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BC_DOCS_ATTACH_HISTORY ADD CONSTRAINT BCFK_ATTACHHISTORY_MODIFIER FOREIGN KEY (MODIFIER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BC_DOCS_ATTACH_HISTORY ADD CONSTRAINT BCFK_ATTACHHISTORY_ATTACH FOREIGN KEY (AID) 
	REFERENCES BC_DOCS_ATTACH (ID);

-- ÓÃ»§·´À¡
CREATE TABLE BC_FEEDBACK (
    ID number(19) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    STATUS_ number(1)  NOT NULL,
    SUBJECT varchar2(500) NOT NULL,
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19),
    MODIFIED_DATE date,
    CONTENT varchar2(4000) NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_FEEDBACK IS 'ÓÃ»§·´À¡';
COMMENT ON COLUMN BC_FEEDBACK.UID_ IS '¹ØÁª¸½¼þµÄ±êÊ¶ºÅ';
COMMENT ON COLUMN BC_FEEDBACK.STATUS_ IS '×´Ì¬:0-²Ý¸å,1-ÒÑÌá½»,2-ÒÑÊÜÀí';
COMMENT ON COLUMN BC_FEEDBACK.FILE_DATE IS '´´½¨Ê±¼ä';
COMMENT ON COLUMN BC_FEEDBACK.SUBJECT IS '±êÌâ';
COMMENT ON COLUMN BC_FEEDBACK.CONTENT IS 'ÏêÏ¸ÄÚÈÝ';

COMMENT ON COLUMN BC_FEEDBACK.AUTHOR_ID IS '´´½¨ÈËID';
COMMENT ON COLUMN BC_FEEDBACK.MODIFIER_ID IS '×îºóÐÞ¸ÄÈËID';
COMMENT ON COLUMN BC_FEEDBACK.MODIFIED_DATE IS '×îºóÐÞ¸ÄÊ±¼ä';
ALTER TABLE BC_FEEDBACK ADD CONSTRAINT BCFK_FEEDBACK_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BC_FEEDBACK ADD CONSTRAINT BCFK_FEEDBACK_MODIFIER FOREIGN KEY (MODIFIER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);


-- ##Ñ¡ÏîÄ£¿é##
-- Ñ¡Ïî·Ö×é
CREATE TABLE BC_OPTION_GROUP (
    ID number(19) NOT NULL,
    KEY_ varchar2(255) NOT NULL,
    VALUE_ varchar2(255) NOT NULL,
    ORDER_ varchar2(100),
    ICON varchar2(100),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_OPTION_GROUP IS 'Ñ¡Ïî·Ö×é';
COMMENT ON COLUMN BC_OPTION_GROUP.KEY_ IS '¼ü';
COMMENT ON COLUMN BC_OPTION_GROUP.VALUE_ IS 'Öµ';
COMMENT ON COLUMN BC_OPTION_GROUP.ORDER_ IS 'ÅÅÐòºÅ';
COMMENT ON COLUMN BC_OPTION_GROUP.ICON IS 'Í¼±êÑùÊ½';
CREATE INDEX BCIDX_OPTIONGROUP_KEYVALUE ON BC_OPTION_GROUP (KEY_,VALUE_);

-- Ñ¡ÏîÌõÄ¿
CREATE TABLE BC_OPTION_ITEM (
    ID number(19) NOT NULL,
    PID number(19) NOT NULL,
    KEY_ varchar2(255) NOT NULL,
    VALUE_ varchar2(255) NOT NULL,
    ORDER_ varchar2(100),
    ICON varchar2(100),
    STATUS_ number(1)  NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_OPTION_ITEM IS 'Ñ¡ÏîÌõÄ¿';
COMMENT ON COLUMN BC_OPTION_ITEM.PID IS 'ËùÊô·Ö×éµÄID';
COMMENT ON COLUMN BC_OPTION_ITEM.KEY_ IS '¼ü';
COMMENT ON COLUMN BC_OPTION_ITEM.VALUE_ IS 'Öµ';
COMMENT ON COLUMN BC_OPTION_ITEM.ORDER_ IS 'ÅÅÐòºÅ';
COMMENT ON COLUMN BC_OPTION_ITEM.ICON IS 'Í¼±êÑùÊ½';
COMMENT ON COLUMN BC_OPTION_ITEM.STATUS_ IS '×´Ì¬£º0-ÆôÓÃÖÐ,1-ÒÑ½ûÓÃ,2-ÒÑÉ¾³ý';
ALTER TABLE BC_OPTION_ITEM ADD CONSTRAINT BCFK_OPTIONITEM_OPTIONGROUP FOREIGN KEY (PID) 
	REFERENCES BC_OPTION_GROUP (ID);
CREATE INDEX BCIDX_OPTIONITEM_KEYVALUE ON BC_OPTION_ITEM (KEY_,VALUE_);

-- ï¿½ï¿½ï¿½ï¿½Identityï¿½Ãµï¿½ï¿½ï¿½ï¿½Ð£ï¿½ï¿½ï¿½Ê¼ï¿½ï¿½1
CREATE sequence CORE_SEQUENCE
    minvalue 1
    start with 1000
    increment by 1
    cache 20;

-- ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×ªï¿½ï¿½ï¿½Ãµï¿½ï¿½ï¿½ï¿½Ð£ï¿½ï¿½ï¿½Ê¼ï¿½ï¿?100000
CREATE sequence DC_SEQUENCE
    minvalue 1
    start with 100000
    increment by 1
    cache 20;

-- ï¿½ï¿½ï¿½×ªï¿½ï¿½ï¿½ï¿½Â?
CREATE TABLE DC_RECORD(
  TYPE_         VARCHAR2(255) NOT NULL,
  FROM_ID       NUMBER(19) NOT NULL,
  TO_ID         NUMBER(19) NOT NULL,
  FROM_TABLE    VARCHAR2(255),
  TO_TABLE      VARCHAR2(255),
  CREATE_DATE   DATE NOT NULL,
  REMARK        VARCHAR2(4000),
  MODIFIED_DATE DATE
);
COMMENT ON TABLE DC_RECORD IS 'ï¿½ï¿½ï¿½×ªï¿½ï¿½ï¿½ï¿½Â?';
COMMENT ON COLUMN DC_RECORD.TYPE_ IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN DC_RECORD.FROM_ID IS 'ï¿½É±ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN DC_RECORD.TO_ID IS 'ï¿½Â±ï¿½ï¿½ï¿½Ýµï¿½ID';
COMMENT ON COLUMN DC_RECORD.FROM_TABLE IS 'ï¿½ï¿½ï¿½ï¿½Ý±ï¿½ï¿½ï¿?';
COMMENT ON COLUMN DC_RECORD.TO_TABLE IS 'ï¿½ï¿½ï¿½ï¿½Ý±ï¿½ï¿½ï¿?';
COMMENT ON COLUMN DC_RECORD.CREATE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN DC_RECORD.REMARK IS 'ï¿½ï¿½×¢Ëµï¿½ï¿½';
COMMENT ON COLUMN DC_RECORD.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
ALTER TABLE DC_RECORD ADD CONSTRAINT UK_RECORD UNIQUE (TYPE_, FROM_ID);

-- bcÓªï¿½Ë¹ï¿½ï¿½ï¿½ï¿½ï¿½ÏµÍ³ï¿½Ä½ï¿½ï¿½ï¿½Å±ï¿?,ï¿½ï¿½ï¿½Ð±ï¿½ï¿½ï¿½ï¿½ë¸½ï¿½ï¿½Ç°×º"BS_"
-- ï¿½ï¿½ï¿½Ð´Ë½Å±ï¿½Ö®Ç°ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ½Ì¨ï¿½Ä½ï¿½ï¿½ï¿½Å±ï¿½framework.db.mysql.CREATE.sql

-- ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ï¢
CREATE TABLE BS_MOTORCADE (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36),
   CODE                 VARCHAR2(255),
   NAME                 VARCHAR2(255)        NOT NULL,
   FULLNAME             VARCHAR2(255),
   PAYMENT_DATE         DATE,
   COMPANY              VARCHAR2(255),
   COLOR                VARCHAR2(255),
   ADDRESS              VARCHAR2(255),
   PRINCIPAL            VARCHAR2(500),
   PHONE                VARCHAR2(255),
   FAX                  VARCHAR2(255),
   DESC_                VARCHAR2(4000),
   STATUS_              NUMBER(1)            NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_MOTORCADE IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE.CODE IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE.NAME IS 'ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_MOTORCADE.FULLNAME IS 'È«ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE.PAYMENT_DATE IS 'ï¿½É·ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE.COMPANY IS 'ï¿½ï¿½Ë¾';
COMMENT ON COLUMN BS_MOTORCADE.COLOR IS 'ï¿½ï¿½É«';
COMMENT ON COLUMN BS_MOTORCADE.ADDRESS IS 'ï¿½ï¿½Ö·';
COMMENT ON COLUMN BS_MOTORCADE.PRINCIPAL IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE.PHONE IS 'ï¿½ç»°';
COMMENT ON COLUMN BS_MOTORCADE.FAX IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE.DESC_ IS 'ï¿½ï¿½×¢';
COMMENT ON COLUMN BS_MOTORCADE.STATUS_ IS '×´Ì¬ï¿½ï¿½0-ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,1-ï¿½Ñ½ï¿½ï¿½ï¿½,2-ï¿½ï¿½É¾ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_MOTORCADE.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_MOTORCADE.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê·ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CREATE TABLE BS_MOTORCADE_CARQUANTITY (
   ID                   NUMBER(19)           NOT NULL,
   MOTORCADE_ID         NUMBER(19)           NOT NULL,
   YEAR_                NUMBER(4)            NOT NULL,
   MONTH_               NUMBER(2)            NOT NULL,
   QUANTITY             NUMBER(19)           NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_MOTORCADE_CARQUANTITY IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê·ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MOTORCADE_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.YEAR_ IS 'ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MONTH_ IS 'ï¿½Â·ï¿½';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.QUANTITY IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);


-- Ö¤ï¿½ï¿½
create table BS_CERT (
    ID number(19) NOT NULL,
    STATUS_ number(1) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    CERT_CODE varchar2(255) NOT NULL,
    CERT_NAME varchar2(255) NOT NULL,
    CERT_FULL_NAME varchar2(255),
    LICENCER varchar2(255),
    ISSUE_DATE date,
    START_DATE date,
    END_DATE date,
    EXT_STR1 varchar2(255),
    EXT_STR2 varchar2(255),
    EXT_STR3 varchar2(255),
    EXT_NUM1 number(19),
    EXT_NUM2 number(19),
    EXT_NUM3 number(19),
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19) ,
    MODIFIED_DATE date,
    primary key (ID)
);
COMMENT ON TABLE BS_CERT IS 'Ö¤ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT.STATUS_ IS '×´Ì¬ï¿½ï¿½0-ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,1-ï¿½Ñ½ï¿½ï¿½ï¿½,2-ï¿½ï¿½É¾ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT.CERT_CODE IS 'Ö¤ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT.CERT_NAME IS 'Ö¤ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT.CERT_FULL_NAME IS 'Ö¤ï¿½ï¿½È«ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT.LICENCER IS 'ï¿½ï¿½Ö¤ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT.START_DATE IS 'ï¿½ï¿½Ð§ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT.ISSUE_DATE IS 'ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT.END_DATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CERT.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CERT.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
ALTER TABLE BS_CERT ADD CONSTRAINT BSFK_CERT_AUTHORID FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CERT ADD CONSTRAINT BSFK_CERT_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
CREATE INDEX BSIDX_CERT_CODE ON BS_CERT (CERT_CODE ASC);
CREATE INDEX BSIDX_CERT_NAME ON BS_CERT (CERT_NAME ASC);

-- Ö¤ï¿½ï¿½:ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö?
create table BS_CERT_IDENTITY (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_IDENTITY IS 'Ö¤ï¿½ï¿½:ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö?';
COMMENT ON COLUMN BS_CERT_IDENTITY.NAME IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_IDENTITY.SEX IS 'ï¿½Ô±ï¿½(0-Î´ï¿½ï¿½ï¿½ï¿½,1-ï¿½ï¿½,2-Å®)';
COMMENT ON COLUMN BS_CERT_IDENTITY.BIRTHDATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_IDENTITY.NATION IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_IDENTITY.ADDRESS IS '×¡Ö·';
ALTER TABLE BS_CERT_IDENTITY ADD CONSTRAINT BSFK_CERT4IDENTITY_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- Ö¤ï¿½ï¿½:ï¿½ï¿½ï¿½ï¿½Ê»Ö¤
create table BS_CERT_DRIVING (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    MODEL varchar2(255),
    RECEIVEDATE date,
    VALIDFOR varchar2(255),
    ARCHIVENO varchar2(255),
    RECORD varchar2(255),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_DRIVING IS 'Ö¤ï¿½ï¿½:ï¿½ï¿½ï¿½ï¿½Ê»Ö¤';
COMMENT ON COLUMN BS_CERT_DRIVING.NAME IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_DRIVING.SEX IS 'ï¿½Ô±ï¿½(0-Î´ï¿½ï¿½ï¿½ï¿½,1-ï¿½ï¿½,2-Å®)';
COMMENT ON COLUMN BS_CERT_DRIVING.BIRTHDATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_DRIVING.NATION IS 'ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_DRIVING.ADDRESS IS 'ï¿½ï¿½Ö·';
COMMENT ON COLUMN BS_CERT_DRIVING.MODEL IS '×¼ï¿½Ý³ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_DRIVING.RECEIVEDATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_DRIVING.VALIDFOR IS 'ï¿½ï¿½Ð§ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_DRIVING.ARCHIVENO IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT_DRIVING.RECORD IS 'ï¿½ï¿½Â¼';
ALTER TABLE BS_CERT_DRIVING ADD CONSTRAINT BSFK_CERT4DRIVING_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- Ö¤ï¿½ï¿½:ï¿½ï¿½Òµï¿½Ê¸ï¿½Ö¤
create table BS_CERT_CYZG (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    SCOPE_ varchar2(255),
    IDENTITY_NO varchar2(255),
    SERVICE_UNIT varchar2(500),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_CYZG IS 'Ö¤ï¿½ï¿½:ï¿½ï¿½Òµï¿½Ê¸ï¿½Ö¤';
COMMENT ON COLUMN BS_CERT_CYZG.NAME IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_CYZG.SEX IS 'ï¿½Ô±ï¿½(0-Î´ï¿½ï¿½ï¿½ï¿½,1-ï¿½ï¿½,2-Å®)';
COMMENT ON COLUMN BS_CERT_CYZG.BIRTHDATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_CYZG.NATION IS 'ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_CYZG.ADDRESS IS 'ï¿½ï¿½Ö·';
COMMENT ON COLUMN BS_CERT_CYZG.SCOPE_ IS 'ï¿½ï¿½Òµï¿½Ê¸ï¿½';
COMMENT ON COLUMN BS_CERT_CYZG.IDENTITY_NO IS 'ï¿½ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT_CYZG.SERVICE_UNIT IS 'ï¿½ï¿½ï¿½ï¿½Î»';
ALTER TABLE BS_CERT_CYZG ADD CONSTRAINT BSFK_CERT4CYZG_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- Ö¤ï¿½ï¿½:ï¿½ï¿½ï¿½ï¿½ï¿½Ê¸ï¿½Ö¤
create table BS_CERT_FWZG (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    LEVEL_ varchar2(255),
    SERVICE_UNIT varchar2(500),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_FWZG IS 'Ö¤ï¿½ï¿½:ï¿½ï¿½ï¿½ï¿½ï¿½Ê¸ï¿½Ö¤';
COMMENT ON COLUMN BS_CERT_FWZG.NAME IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_FWZG.SEX IS 'ï¿½Ô±ï¿½(0-Î´ï¿½ï¿½ï¿½ï¿½,1-ï¿½ï¿½,2-Å®)';
COMMENT ON COLUMN BS_CERT_FWZG.BIRTHDATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_FWZG.NATION IS 'ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_FWZG.ADDRESS IS 'ï¿½ï¿½Ö·';
COMMENT ON COLUMN BS_CERT_FWZG.LEVEL_ IS 'ï¿½È¼ï¿½';
COMMENT ON COLUMN BS_CERT_FWZG.SERVICE_UNIT IS 'ï¿½ï¿½ï¿½ï¿½Î»';
ALTER TABLE BS_CERT_FWZG ADD CONSTRAINT BSFK_CERT4FWZG_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- Ö¤ï¿½ï¿½:ï¿½ï¿½Ê»ï¿½ï¿½ÑµÖ¤
create table BS_CERT_JSPX (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    DOMAIN varchar2(255),
    TRAIN_DATE date,
    TRAIN_HOUR number(3),
    GRADE1 number(3),
    GRADE2 varchar2(10),
    GRADE3 varchar2(10),
    IDENTITY_NO varchar2(255),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_JSPX IS 'Ö¤ï¿½ï¿½:ï¿½ï¿½Ê»ï¿½ï¿½ÑµÖ¤';
COMMENT ON COLUMN BS_CERT_JSPX.NAME IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_JSPX.SEX IS 'ï¿½Ô±ï¿½(0-Î´ï¿½ï¿½ï¿½ï¿½,1-ï¿½ï¿½,2-Å®)';
COMMENT ON COLUMN BS_CERT_JSPX.BIRTHDATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_JSPX.NATION IS 'ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_JSPX.ADDRESS IS 'ï¿½ï¿½Ö·';
COMMENT ON COLUMN BS_CERT_JSPX.DOMAIN IS 'ï¿½ï¿½Ñµ×¨Òµ';
COMMENT ON COLUMN BS_CERT_JSPX.TRAIN_DATE IS 'ï¿½ï¿½ÑµÊ±ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_JSPX.TRAIN_HOUR IS 'ï¿½ï¿½ÑµÑ§Ê±';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE1 IS 'ï¿½ï¿½ï¿½ï¿½ÖªÊ¶ï¿½ï¿½ï¿½Ë³É¼ï¿½';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE2 IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü¿ï¿½ï¿½Ë³É¼ï¿½';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE3 IS 'ï¿½ï¿½ï¿½ï¿½ï¿½É¼ï¿½';
COMMENT ON COLUMN BS_CERT_JSPX.IDENTITY_NO IS 'ï¿½ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½ï¿?';
ALTER TABLE BS_CERT_JSPX ADD CONSTRAINT BSFK_CERT4JSPX_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- Ö¤ï¿½ï¿½:ï¿½ï¿½Â·ï¿½ï¿½ï¿½ï¿½Ö¤
CREATE TABLE BS_CERT_ROADTRANSPORT(
	ID                   NUMBER(19) NOT NULL,
	FACTORY              VARCHAR2(255),
	PLATE                VARCHAR2(255),
	OWNER                VARCHAR2(255),
	ADDRESS              VARCHAR2(255),
	BS_CERT_NO           VARCHAR2(255),
	SEAT                 VARCHAR2(255),
	DIM_LEN              NUMBER(19),
	DIM_WIDTH            NUMBER(19),
	DIM_HEIGHT           NUMBER(19),
	SCOPE_               VARCHAR2(255),
	LEVEL_               VARCHAR2(255),
  PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CERT_ROADTRANSPORT IS 'Ö¤ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â·ï¿½ï¿½ï¿½ï¿½Ö¤';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.FACTORY IS 'Æ·ï¿½ï¿½ï¿½ÍºÅ£ï¿½ï¿½ç¡°É£ï¿½ï¿½ï¿½ï¿½SVW7182QQDï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.PLATE IS 'ï¿½ï¿½ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ë£¬ï¿½ç¡°ï¿½ï¿½AC4X74ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.OWNER IS 'Òµï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.ADDRESS IS 'ï¿½ï¿½Ö·';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.BS_CERT_NO IS 'ï¿½ï¿½Óªï¿½ï¿½ï¿½Ö¤ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.SEAT IS 'ï¿½Ö£ï¿½ï¿½ï¿½Î»';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_LEN IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_WIDTH IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿??ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_HEIGHT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿½ß£ï¿½ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.SCOPE_ IS 'ï¿½ï¿½Óªï¿½ï¿½Î§';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.LEVEL_ IS 'ï¿½ï¿½ï¿½ï¿½ï¿½È¼ï¿½';
ALTER TABLE BS_CERT_ROADTRANSPORT ADD CONSTRAINT BSFK_CERT4ROADTRANSPORT_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);
  
-- Ö¤ï¿½ï¿½:ï¿½ï¿½ï¿½ï¿½Ê»Ö¤
CREATE TABLE BS_CERT_VEHICELICENSE(
	ID                   NUMBER(19) NOT NULL,
	FACTORY              VARCHAR2(255),
	PLATE                VARCHAR2(255),
	OWNER                VARCHAR2(255),
	ADDRESS              VARCHAR2(255),
	USE_CHARACTER        VARCHAR2(255),
	VEHICE_TYPE          VARCHAR2(255),
	VIN                  VARCHAR2(255),
	ENGINE_NO            VARCHAR2(255),
	REGISTER_DATE        DATE,
	ARCHIVE_NO           VARCHAR2(255),
	DIM_LEN              number(19),
	DIM_WIDTH            number(19),
	DIM_HEIGHT           number(19),
	TOTAL_WEIGHT         number(19),
	CURB_WEIGHT          number(19),
	ACCESS_WEIGHT        number(19),
	ACCESS_COUNT         number(19),
	SCRAP_DATE           DATE,
	DESC_                VARCHAR2(500),
	RECORD_              VARCHAR2(500),
	PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CERT_VEHICELICENSE IS 'Ö¤ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê»Ö¤';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.FACTORY IS 'Æ·ï¿½ï¿½ï¿½ÍºÅ£ï¿½ï¿½ç¡°É£ï¿½ï¿½ï¿½ï¿½SVW7182QQDï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.PLATE IS 'ï¿½ï¿½ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ë£¬ï¿½ç¡°ï¿½ï¿½AC4X74ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.OWNER IS 'Òµï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ADDRESS IS 'ï¿½ï¿½Ö·';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.USE_CHARACTER IS 'Ê¹ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.VEHICE_TYPE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.VIN IS 'ï¿½ï¿½ï¿½ï¿½Ê¶ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ENGINE_NO IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.REGISTER_DATE IS '×¢ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ARCHIVE_NO IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_LEN IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_WIDTH IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿??ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_HEIGHT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿½ß£ï¿½ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.TOTAL_WEIGHT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»KG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.CURB_WEIGHT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»KG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ACCESS_WEIGHT IS 'ï¿½Ë¶ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»KG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ACCESS_COUNT IS 'ï¿½Ë¶ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.SCRAP_DATE IS 'Ç¿ï¿½Æ±ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DESC_ IS 'ï¿½ï¿½×¢';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.RECORD_ IS 'ï¿½ï¿½ï¿½ï¿½ï¿½Â?';
ALTER TABLE BS_CERT_VEHICELICENSE ADD CONSTRAINT BSFK_CERT4VEHICELICENSE_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);


-- Ë¾ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
create table BS_CARMAN (
    ID number(19) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    STATUS_ number(1) NOT NULL,
    TYPE_ number(1) default 0 NOT NULL,
    NAME varchar2(255) NOT NULL,
    ORDER_ varchar2(100),
    SEX number(1) default 0 NOT NULL,
    WORK_DATE date,
    ORIGIN varchar2(255),
    REGION_  number(1),
    HOUSE_TYPE varchar2(255),
    BIRTHDATE date,
    FORMER_UNIT varchar2(500),
    ADDRESS varchar2(500),
    ADDRESS1 varchar2(500),
    PHONE varchar2(500),
    PHONE1 varchar2(500),
    MODEL_                VARCHAR2(255),
	LEVEL_ varchar2(255),
    CERT_IDENTITY        VARCHAR2(255),
    CERT_DRIVING         VARCHAR2(255),
    CERT_DRIVING_ARCHIVE VARCHAR2(255),
    CERT_DRIVING_FIRST_DATE DATE,
    CERT_DRIVING_START_DATE DATE,
    CERT_DRIVING_END_DATE DATE,
    CERT_FWZG            VARCHAR2(255),
    CERT_CYZG            VARCHAR2(255),
    DRIVING_STATUS        number(1),
    EXT_FZJG             VARCHAR2(255),
    EXT_ZRR              VARCHAR2(255),
    GZ                   number(1),
    ACCESS_CERTS         VARCHAR2(255),
    DESC_                VARCHAR2(4000),
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19),
    MODIFIED_DATE date,
    primary key (ID)
);
COMMENT ON TABLE BS_CARMAN IS 'Ë¾ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.UID_ IS 'UID';
COMMENT ON COLUMN BS_CARMAN.STATUS_ IS '×´Ì¬ï¿½ï¿½0-ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,1-ï¿½Ñ½ï¿½ï¿½ï¿½,2-ï¿½ï¿½É¾ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.TYPE_ IS 'ï¿½ï¿½ï¿?:0-Ë¾ï¿½ï¿½,1-ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,2-Ë¾ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN.NAME IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.ORDER_ IS 'ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN.SEX IS 'ï¿½Ô±ï¿½0-Î´ï¿½ï¿½ï¿½ï¿½,1-ï¿½ï¿½,2-Å®';
COMMENT ON COLUMN BS_CARMAN.WORK_DATE IS 'ï¿½ï¿½Ö°ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.ORIGIN IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.REGION_ IS 'ï¿½ï¿½ï¿½ï¿½0-Î´ï¿½ï¿½ï¿½å£¬1-ï¿½ï¿½ï¿½Ð£ï¿½2-ï¿½ï¿½Ê¡ï¿½ï¿½3-ï¿½ï¿½Ê¡';
COMMENT ON COLUMN BS_CARMAN.HOUSE_TYPE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.BIRTHDATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.FORMER_UNIT IS 'ï¿½ï¿½Ö°Ô­ï¿½ï¿½Î»';
COMMENT ON COLUMN BS_CARMAN.ADDRESS IS 'ï¿½ï¿½ï¿½Ö¤×¡Ö?';
COMMENT ON COLUMN BS_CARMAN.ADDRESS1 IS 'ï¿½ï¿½×¡ï¿½ï¿½Ö·';
COMMENT ON COLUMN BS_CARMAN.PHONE IS 'ï¿½ç»°';
COMMENT ON COLUMN BS_CARMAN.PHONE1 IS 'ï¿½ç»°1';
COMMENT ON COLUMN BS_CARMAN.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN.MODEL_ IS '×¼ï¿½Ý³ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.LEVEL_ IS 'Ë¾ï¿½ï¿½È¼ï¿?';
COMMENT ON COLUMN BS_CARMAN.CERT_IDENTITY IS 'ï¿½ï¿½ï¿½Ö¤ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING IS 'ï¿½ï¿½Ê»Ö¤ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_ARCHIVE IS 'ï¿½ï¿½Ê»Ö¤ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_FIRST_DATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_START_DATE IS 'ï¿½ï¿½Ê»Ö¤ï¿½ï¿½Ð§ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_END_DATE IS 'ï¿½ï¿½Ê»Ö¤ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.CERT_FWZG IS 'ï¿½ï¿½ï¿½ï¿½ï¿½Ê¸ï¿½Ö¤ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.CERT_CYZG IS 'ï¿½ï¿½Òµï¿½Ê¸ï¿½Ö¤ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.DRIVING_STATUS IS 'ï¿½ï¿½Ê»×´Ì¬ï¿½ï¿½0-Î´ï¿½ï¿½ï¿½å£¬1-ï¿½ï¿½à£?2-ï¿½ï¿½ï¿½à£¬3-ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.EXT_FZJG IS 'ï¿½ï¿½Ö§ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê·ï¿½ï¿½ÝµÄ±ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN.EXT_ZRR IS 'ï¿½ï¿½ï¿½ï¿½ï¿½Ë£ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê·ï¿½ï¿½ÝµÄ±ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN.GZ IS 'ï¿½ï¿½Ê»Ö¤ï¿½Ç·ï¿½ï¿½ï¿½ï¿?:0-ï¿½ï¿½,1-ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN.ACCESS_CERTS IS 'ï¿½Ñ¿ï¿½È¡Ö¤ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê·ï¿½ï¿½Ý±ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN.DESC_ IS 'ï¿½ï¿½×¢';
ALTER TABLE BS_CARMAN ADD CONSTRAINT BSFK_CARMAN_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CARMAN ADD CONSTRAINT BSFK_CARMAN_MODIFIER FOREIGN KEY (MODIFIER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- Ë¾ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½Ä¹ï¿½ï¿½ï¿½
CREATE TABLE BS_CARMAN_CERT (
    MAN_ID number(19) NOT NULL,
    CERT_ID number(19) NOT NULL,
    PRIMARY KEY (MAN_ID,CERT_ID)
);
COMMENT ON TABLE BS_CARMAN_CERT IS 'Ë¾ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½Ä¹ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN_CERT.MAN_ID IS 'Ë¾ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN_CERT.CERT_ID IS 'Ö¤ï¿½ï¿½ID';
ALTER TABLE BS_CARMAN_CERT ADD CONSTRAINT BSFK_CARMANCERT_MAN FOREIGN KEY (MAN_ID) 
	REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_CERT ADD CONSTRAINT BSFK_CARMANCERT_CERT FOREIGN KEY (CERT_ID) 
	REFERENCES BS_CERT (ID);


-- ï¿½ï¿½ï¿½ï¿½ 
CREATE TABLE BS_CAR (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   UNIT_ID              NUMBER(19)           NOT NULL,
   MOTORCADE_ID         NUMBER(19)           NOT NULL,
   BS_TYPE              VARCHAR2(255),
   CODE                 VARCHAR2(255),
   ORIGIN_NO            VARCHAR2(255),
   PLATE_TYPE           VARCHAR2(255),
   PLATE_NO             VARCHAR2(255),
   VIN                  VARCHAR2(255),
   FACTORY_TYPE         VARCHAR2(255),
   FACTORY_MODEL        VARCHAR2(255),
   REGISTER_DATE        DATE,
   OPERATE_DATE         DATE,
   SCRAP_DATE           DATE,
   FACTORY_DATE         DATE,
   REGISTER_NO          VARCHAR2(255),
   LEVEL_               VARCHAR2(255),
   COLOR                VARCHAR2(255),
   RNGINE_NO            VARCHAR2(255),
   RNGINE_TYPE          VARCHAR2(255),
   FUEL_TYPE            VARCHAR2(255),
   DISPLACEMENT         NUMBER(19),
   POWER                NUMBER(19,2),
   TURN_TYPE            VARCHAR2(255),
   TIRE_COUNT           NUMBER(19),
   TIRE_STANDARD        VARCHAR2(255),
   AXIS_DISTANCE        NUMBER(19),
   AXIS_COUNT           NUMBER(19),
   PIECE_COUNT          NUMBER(19),
   DIM_LEN              NUMBER(19),
   DIM_WIDTH            NUMBER(19),
   DIM_HEIGHT           NUMBER(19),
   TOTAL_WEIGHT         NUMBER(19),
   ACCESS_WEIGHT        NUMBER(19),
   ACCESS_COUNT         NUMBER(19),
   ORIGINAL_VALUE       NUMBER(19,2),
   INVOICE_NO1          VARCHAR2(255),
   INVOICE_NO2          VARCHAR2(255),
   PAYMENT_TYPE         VARCHAR2(255),
   CERT_NO1             VARCHAR2(255),
   CERT_NO2             VARCHAR2(255),
   CERT_NO3             VARCHAR2(255),
   TAXIMETER_FACTORY    VARCHAR2(255),
   TAXIMETER_TYPE       VARCHAR2(255),
   TAXIMETER_NO         VARCHAR2(255),
   DESC1                VARCHAR2(4000),
   DESC2                VARCHAR2(4000),
   DESC3                VARCHAR2(4000),
   FILE_DATE            DATE NOT NULL,
   AUTHOR_ID            NUMBER(19) NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CAR IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.STATUS_ IS '×´Ì¬ï¿½ï¿½0-ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,1-ï¿½Ñ½ï¿½ï¿½ï¿½,2-ï¿½ï¿½É¾ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.UNIT_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»ID';
COMMENT ON COLUMN BS_CAR.MOTORCADE_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CAR.BS_TYPE IS 'Óªï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.CODE IS 'ï¿½Ô±ï¿½ï¿?';
COMMENT ON COLUMN BS_CAR.ORIGIN_NO IS 'Ô­ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.PLATE_TYPE IS 'ï¿½ï¿½ï¿½Æ¹ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç¡°ï¿½ï¿½Aï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.PLATE_NO IS 'ï¿½ï¿½ï¿½Æºï¿½ï¿½ë£¬ï¿½ç¡°C4X74ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.VIN IS 'ï¿½ï¿½ï¿½ï¿½Ê¶ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.FACTORY_TYPE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í£ï¿½ï¿½ç¡°É£ï¿½ï¿½ï¿½É¡ï¿½';
COMMENT ON COLUMN BS_CAR.FACTORY_MODEL IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ÍºÅ£ï¿½ï¿½ç¡°SVW7182QQDï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.REGISTER_DATE IS 'ï¿½Ç¼ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.OPERATE_DATE IS 'Í¶ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.SCRAP_DATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.FACTORY_DATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.REGISTER_NO IS 'ï¿½ï¿½ï¿½Ç¼Ç±ï¿½ï¿?';
COMMENT ON COLUMN BS_CAR.LEVEL_ IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.COLOR IS 'ï¿½ï¿½É«';
COMMENT ON COLUMN BS_CAR.RNGINE_NO IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CAR.RNGINE_TYPE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.FUEL_TYPE IS 'È¼ï¿½ï¿½ï¿½ï¿½ï¿½Í£ï¿½ï¿½ç¡°ï¿½ï¿½ï¿½Í¡ï¿½';
COMMENT ON COLUMN BS_CAR.DISPLACEMENT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»ML';
COMMENT ON COLUMN BS_CAR.POWER IS 'ï¿½ï¿½ï¿½Ê£ï¿½ï¿½ï¿½Î»KW';
COMMENT ON COLUMN BS_CAR.TURN_TYPE IS '×ªï¿½ï¿½Ê½ï¿½ï¿½ï¿½ç¡°ï¿½ï¿½ï¿½ï¿½ï¿½Ì¡ï¿½';
COMMENT ON COLUMN BS_CAR.TIRE_COUNT IS 'ï¿½ï¿½Ì¥ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.TIRE_STANDARD IS 'ï¿½ï¿½Ì¥ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CAR.AXIS_DISTANCE IS 'ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CAR.AXIS_COUNT IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.PIECE_COUNT IS 'ï¿½ï¿½ï¿½ï¿½Ö°åµ¯ï¿½ï¿½Æ¬ï¿½ï¿?';
COMMENT ON COLUMN BS_CAR.DIM_LEN IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CAR.DIM_WIDTH IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿??ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CAR.DIM_HEIGHT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ß´ç£ºï¿½ß£ï¿½ï¿½ï¿½Î»MM';
COMMENT ON COLUMN BS_CAR.TOTAL_WEIGHT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»KG';
COMMENT ON COLUMN BS_CAR.ACCESS_WEIGHT IS 'ï¿½Ë¶ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»KG';
COMMENT ON COLUMN BS_CAR.ACCESS_COUNT IS 'ï¿½Ë¶ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.ORIGINAL_VALUE IS 'ï¿½Ì¶ï¿½ï¿½Ê²ï¿½Ô­Öµï¿½ï¿½ï¿½ï¿½Î»Ôª';
COMMENT ON COLUMN BS_CAR.INVOICE_NO1 IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ±ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.INVOICE_NO2 IS 'ï¿½ï¿½ï¿½ï¿½Ë°ï¿½ï¿½Æ±ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.PAYMENT_TYPE IS 'ï¿½É·ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.CERT_NO1 IS 'ï¿½ï¿½ï¿½ï¿½Ë°Ö¤ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.CERT_NO2 IS 'ï¿½ï¿½ÓªÈ¨Ê¹ï¿½ï¿½Ö¤ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.CERT_NO3 IS 'Ç¿ï¿½ï¿½Ö¤ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.TAXIMETER_FACTORY IS 'ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ì³§';
COMMENT ON COLUMN BS_CAR.TAXIMETER_TYPE IS 'ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½Íºï¿½';
COMMENT ON COLUMN BS_CAR.TAXIMETER_NO IS 'ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CAR.DESC1 IS 'ï¿½ï¿½×¢1';
COMMENT ON COLUMN BS_CAR.DESC2 IS 'ï¿½ï¿½×¢2';
COMMENT ON COLUMN BS_CAR.DESC3 IS 'ï¿½ï¿½×¢3';
COMMENT ON COLUMN BS_CAR.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CAR.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CAR.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_MOTORCADEID FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_UNITID FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);

-- ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½Ä¹ï¿½ï¿½ï¿½
CREATE TABLE BS_CAR_CERT (
    CAR_ID number(19) NOT NULL,
    CERT_ID number(19) NOT NULL,
    PRIMARY KEY (CAR_ID,CERT_ID)
);
COMMENT ON TABLE BS_CAR_CERT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö¤ï¿½ï¿½ï¿½Ä¹ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR_CERT.CAR_ID IS 'ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CAR_CERT.CERT_ID IS 'Ö¤ï¿½ï¿½ID';
ALTER TABLE BS_CAR_CERT ADD CONSTRAINT BSFK_CARCERT_CAR FOREIGN KEY (CAR_ID) 
	REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_CERT ADD CONSTRAINT BSFK_CARCERT_CERT FOREIGN KEY (CERT_ID) 
	REFERENCES BS_CERT (ID);


-- ï¿½ï¿½Í¬
CREATE TABLE BS_CONTRACT (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   WORD_NO              VARCHAR2(255),
   CODE                 VARCHAR2(255)        NOT NULL,
   TYPE_                NUMBER(1)	     NOT NULL,
   TRANSACTOR_ID        NUMBER(19)           NOT NULL,
   SIGN_DATE            DATE                 NOT NULL,
   START_DATE           DATE                 NOT NULL,
   END_DATE             DATE                 NOT NULL,
   CONTENT              VARCHAR2(4000),
   EXT_STR1             VARCHAR2(255),
   EXT_STR2             VARCHAR2(255),
   EXT_STR3             VARCHAR2(255),
   EXT_NUM1             NUMBER(19),
   EXT_NUM2             NUMBER(19),
   EXT_NUM3             NUMBER(19),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CONTRACT IS 'ï¿½ï¿½Í¬';
COMMENT ON COLUMN BS_CONTRACT.STATUS_ IS '×´Ì¬ï¿½ï¿½0-ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,1-ï¿½Ñ½ï¿½ï¿½ï¿½,2-ï¿½ï¿½É¾ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT.WORD_NO IS 'ï¿½ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CONTRACT.CODE IS 'ï¿½ï¿½Í¬ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT.TYPE_ IS 'ï¿½ï¿½Í¬ï¿½ï¿½ï¿½Í£ï¿½ï¿½ï¿½ï¿½Í¶ï¿½ï¿½ï¿½Í¬ï¿½ï¿½ï¿½Ð°ï¿½ï¿½Í¬ï¿½ï¿?';
COMMENT ON COLUMN BS_CONTRACT.TRANSACTOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CONTRACT.SIGN_DATE IS 'Ç©ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT.START_DATE IS 'ï¿½ï¿½Ð§ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT.END_DATE IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT.CONTENT IS 'ï¿½ï¿½Í¬ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR1 IS 'ï¿½Ö·ï¿½ï¿½ï¿½Õ¹ï¿½ï¿½1';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR2 IS 'ï¿½Ö·ï¿½ï¿½ï¿½Õ¹ï¿½ï¿½2';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR3 IS 'ï¿½Ö·ï¿½ï¿½ï¿½Õ¹ï¿½ï¿½3';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM1 IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Õ¹ï¿½ï¿½1';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM2 IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Õ¹ï¿½ï¿½2';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM3 IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Õ¹ï¿½ï¿½3';
COMMENT ON COLUMN BS_CONTRACT.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CONTRACT.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CONTRACT.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTRACT_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTRACT_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- Ë¾ï¿½ï¿½ï¿½Í¶ï¿½ï¿½ï¿½Í¬
CREATE TABLE BS_CONTRACT_LABOUR (
   ID                   NUMBER(19)           NOT NULL,
   DRIVER_ID            NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   ADDITION_PROTOCOL    NUMBER(1)            NOT NULL,
   PRE_INDUSTRY_NAME    VARCHAR2(255),
   PRE_INDUSTRY_TYPE    NUMBER(1)            NOT NULL,
   HIRING_PROCEDURE     NUMBER(1)            NOT NULL,
   DOLE                 NUMBER(1)            NOT NULL,
   FILING               NUMBER(1)            NOT NULL,
   CERT_NO              VARCHAR2(255)        NOT NULL,
   CONSTRAINT PK_BS_CONTRACT_LABOUR PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CONTRACT_LABOUR IS 'Ë¾ï¿½ï¿½ï¿½Í¶ï¿½ï¿½ï¿½Í¬';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.DRIVER_ID IS 'Ë¾ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.CAR_ID IS 'ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.ADDITION_PROTOCOL IS 'ï¿½ï¿½ï¿½ï¿½Ð­ï¿½ï¿½:0-ï¿½ï¿½,1-ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.PRE_INDUSTRY_NAME IS 'Ç°ï¿½ï¿½ï¿½ï¿½Òµï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.PRE_INDUSTRY_TYPE IS 'Ç°ï¿??ï¿½ï¿½ï¿½ï¿½Òµ:0-ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,1-ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.HIRING_PROCEDURE IS 'ï¿½ï¿½ï¿½Ã¹ï¿½ï¿½ï¿½ï¿½ï¿½:0-Î´ï¿½ï¿½,1-ï¿½Ñ°ï¿½';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.DOLE IS 'ï¿½Â¸ï¿½Ê§Òµï¿½ï¿½ï¿½ï¿½:0-ï¿½Ñ·ï¿½,1-Î´ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.FILING IS 'ï¿½Ç·ï¿½ï¿½Ñ±ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.CERT_NO IS 'ï¿½Ê¸ï¿½Ö¤ï¿½ï¿½';
ALTER TABLE BS_CONTRACT_LABOUR ADD CONSTRAINT BSFK_CONTRACT4LABOUR_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CONTRACT_LABOUR ADD CONSTRAINT BSFK_CONTRACT4LABOUR_CARMAN FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CONTRACT_LABOUR ADD CONSTRAINT BSFK_CONTRACT4LABOUR_CONTRACT FOREIGN KEY (ID)
      REFERENCES BS_CONTRACT (ID);

-- ï¿½ï¿½ï¿½ï¿½ï¿½Ëºï¿½Í¬
CREATE TABLE BS_CONTRACT_CHARGER (
   ID                   NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   SIGN_TYPE            VARCHAR2(255)        NOT NULL,
   LOGOUT               NUMBER(1)            NOT NULL,
   TAKEBACK_ORIGIN      NUMBER(1)            NOT NULL,
   INCLUDE_COST         NUMBER(1)            NOT NULL,
   OLD_CONTENT          VARCHAR2(4000),
   CONSTRAINT PK_BS_CONTRACT_CHARGER PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CONTRACT_CHARGER IS 'ï¿½ï¿½ï¿½ï¿½ï¿½Ëºï¿½Í¬:ï¿½ï¿½Ð°ï¿½ï¿½Í¬';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.CAR_ID IS 'ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.SIGN_TYPE IS 'Ç©Ô¼ï¿½ï¿½ï¿½ï¿½:ï¿½ï¿½ï¿½Â»ï¿½';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.LOGOUT IS '×¢ï¿½ï¿½:0-Î´,1-ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.TAKEBACK_ORIGIN IS 'ï¿½Ñ¾ï¿½ï¿½Õ»ï¿½Ô­ï¿½ï¿½:0-Î´1-ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.INCLUDE_COST IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½:0-ï¿½ï¿½ï¿½ï¿½,1-ï¿½ï¿½';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.OLD_CONTENT IS 'ï¿½Éºï¿½Í¬ï¿½ï¿½ï¿½ï¿½';
ALTER TABLE BS_CONTRACT_CHARGER ADD CONSTRAINT BSFK_CONTRACT4CHARGER_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CONTRACT_CHARGER ADD CONSTRAINT BSFK_CONTRACT4CHARGER_CONTRACT FOREIGN KEY (ID)
      REFERENCES BS_CONTRACT (ID);

-- ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í¬ï¿½Ä¹ï¿½ï¿½ï¿?
CREATE TABLE BS_CARMAN_CONTRACT (
   CONTRACT_ID          NUMBER(19)           NOT NULL,
   CARMAN_ID            NUMBER(19)           NOT NULL,
   CONSTRAINT PK_BS_CARMAN_CONTRACT PRIMARY KEY (CARMAN_ID, CONTRACT_ID)
);
COMMENT ON TABLE BS_CARMAN_CONTRACT IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í¬ï¿½Ä¹ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN_CONTRACT.CONTRACT_ID IS 'ï¿½ï¿½Í¬ID';
COMMENT ON COLUMN BS_CARMAN_CONTRACT.CARMAN_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
ALTER TABLE BS_CARMAN_CONTRACT ADD CONSTRAINT BSFK_CARMANCONTRACT_CARMAN FOREIGN KEY (CARMAN_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_CONTRACT ADD CONSTRAINT BSFK_CARMANCONTRACT_CONTRACT FOREIGN KEY (CONTRACT_ID)
      REFERENCES BS_CONTRACT_CHARGER (ID);

-- Ë¾ï¿½ï¿½Óªï¿½Ë³ï¿½ï¿½ï¿½
CREATE TABLE BS_CAR_DRIVER (
   ID                   NUMBER(19)           NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   DRIVER_ID            NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   CLASSES              NUMBER(1)            NOT NULL,
   START_DATE           DATE,
   END_DATE             DATE,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   DESC_                VARCHAR2(4000),
  CONSTRAINT PK_BS_CAR_DRIVER PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CAR_DRIVER IS 'Ë¾ï¿½ï¿½Óªï¿½Ë³ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR_DRIVER.STATUS_ IS '×´Ì¬ï¿½ï¿½0-ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,1-ï¿½Ñ½ï¿½ï¿½ï¿½,2-ï¿½ï¿½É¾ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR_DRIVER.DRIVER_ID IS 'Ë¾ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CAR_DRIVER.CAR_ID IS 'ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CAR_DRIVER.CLASSES IS 'Óªï¿½Ë°ï¿½ï¿?:ï¿½ï¿½0-Î´ï¿½ï¿½ï¿½å£¬1-ï¿½ï¿½à¡?2-ï¿½ï¿½ï¿½à¡¢3-ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR_DRIVER.START_DATE IS 'ï¿½ï¿½Ê¼Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR_DRIVER.END_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR_DRIVER.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_CAR_DRIVER.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CAR_DRIVER.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
COMMENT ON COLUMN BS_CAR_DRIVER.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CAR_DRIVER.DESC_ IS 'ï¿½ï¿½×¢';
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_CARMAN FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
      
-- Ë¾ï¿½ï¿½Ç¨ï¿½ï¿½ï¿½ï¿½Ê·
CREATE TABLE BS_CARMAN_HISTORY (
   ID                   NUMBER(19)           NOT NULL,
   TYPE_                VARCHAR2(255)        NOT NULL,
   DRIVER_ID            NUMBER(19)           NOT NULL,
   SUBJECT              VARCHAR2(1000),
   FROM_CARID           NUMBER(19),
   TO_CARID             NUMBER(19)           NOT NULL,
   FROM_CLASSES         VARCHAR2(255),
   TO_CLASSES           VARCHAR2(255)        NOT NULL,
   SHIFT_DATE           DATE                 NOT NULL,
   FROM_MOTORCADEID     NUMBER(19),
   TO_MOTORCADEID       NUMBER(19)           NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   CONSTRAINT PK_BS_CARMAN_HISTORY PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CARMAN_HISTORY IS 'Ë¾ï¿½ï¿½Ç¨ï¿½ï¿½ï¿½ï¿½Ê·';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TYPE_ IS 'Ç¨ï¿½ï¿½ï¿½ï¿½ï¿½Ô£ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö°';
COMMENT ON COLUMN BS_CARMAN_HISTORY.DRIVER_ID IS 'Ë¾ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.SUBJECT IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_CARID IS 'Ç¨ï¿½Ô³ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_CARID IS 'Ç¨ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_CLASSES IS 'Ô­Óªï¿½Ë°ï¿½ï¿?:ï¿½ï¿½ï¿½ï¿½à¡¢ï¿½ï¿½ï¿½à¡¢ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_CLASSES IS 'ï¿½ï¿½Óªï¿½Ë°ï¿½ï¿?:ï¿½ï¿½ï¿½ï¿½à¡¢ï¿½ï¿½ï¿½à¡¢ï¿½ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN_HISTORY.SHIFT_DATE IS 'Ç¨ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_MOTORCADEID IS 'Ô­ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_MOTORCADEID IS 'Ç¨ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_CARMAN_HISTORY.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
COMMENT ON COLUMN BS_CARMAN_HISTORY.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_DRIVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_FROMCAR FOREIGN KEY (FROM_CARID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_TOCAR FOREIGN KEY (TO_CARID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_FROMMOTORCADE FOREIGN KEY (FROM_MOTORCADEID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_TOMOTORCADE FOREIGN KEY (TO_MOTORCADEID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANHISTORY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANHISTORY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ï¿½ï¿½ï¿½ï¿½ALTER TABLE BS_BLACKLIST
CREATE TABLE BS_BLACKLIST (
   ID                   NUMBER(19)           NOT NULL,
   TYPE_                VARCHAR2(255)        NOT NULL,
   UNIT_ID              number(19),
   DRIVER_ID            NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   MOTORCADE_ID         NUMBER(19),
   SUBJECT              VARCHAR2(1000)       NOT NULL,
   LOCK_DATE            DATE                 NOT NULL,
   UNLOCK_DATE          DATE,
   LOCKER_ID            NUMBER(19)           NOT NULL,
   UNLOCKER_ID          NUMBER(19),
   LOCK_REASON          VARCHAR2(4000),
   UNLOCK_REASON        VARCHAR2(4000),
   LEVEL_               VARCHAR2(255),
   CODE                 VARCHAR2(255),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   CONSTRAINT PK_BS_BLACKLIST PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_BLACKLIST IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_BLACKLIST.TYPE_ IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä¿';
COMMENT ON COLUMN BS_BLACKLIST.UNIT_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î»ID';
COMMENT ON COLUMN BS_BLACKLIST.DRIVER_ID IS 'Ë¾ï¿½ï¿½ID';
COMMENT ON COLUMN BS_BLACKLIST.CAR_ID IS 'ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_BLACKLIST.MOTORCADE_ID IS 'ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_BLACKLIST.SUBJECT IS 'ï¿½ï¿½ï¿½ï¿½';
COMMENT ON COLUMN BS_BLACKLIST.LOCK_DATE IS 'ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCK_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_BLACKLIST.LOCKER_ID IS 'ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCKER_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_BLACKLIST.LOCK_REASON IS 'ï¿½ï¿½Ô­ï¿½ï¿½';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCK_REASON IS 'ï¿½ï¿½ï¿½ï¿½Ô­ï¿½ï¿½';
COMMENT ON COLUMN BS_BLACKLIST.LEVEL_ IS 'ï¿½È¼ï¿½';
COMMENT ON COLUMN BS_BLACKLIST.CODE IS 'ï¿½ï¿½ï¿?';
COMMENT ON COLUMN BS_BLACKLIST.FILE_DATE IS 'ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½';
COMMENT ON COLUMN BS_BLACKLIST.AUTHOR_ID IS 'ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ID';
COMMENT ON COLUMN BS_BLACKLIST.MODIFIED_DATE IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½Ê±ï¿½ï¿?';
COMMENT ON COLUMN BS_BLACKLIST.MODIFIER_ID IS 'ï¿½ï¿½ï¿½ï¿½Þ¸ï¿½ï¿½ï¿½ID';
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_UNIT FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_DIRVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_LOCKER FOREIGN KEY (LOCKER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_UNLOCKER FOREIGN KEY (UNLOCKER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

