-- ###########################################################################
-- 宝城综合应用系统的升级脚本
-- 数据库类型: postgresql
-- 升级版本: 从 0.9 升级到 1.0
-- ###########################################################################


-- ## 营运事件基表
-- 删除结案人外键
ALTER TABLE BS_CASE_BASE DROP CONSTRAINT BSFK_CASEBASE_CLOSER;
-- 新增结案人外键
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_CLOSER FOREIGN KEY (CLOSER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ## 表扬
-- 删除经办人外键
ALTER TABLE BS_CASE_PRAISE DROP CONSTRAINT BSFK_PRAISE_RECEIVER;

-- 新增经办人外键
ALTER TABLE BS_CASE_PRAISE ADD CONSTRAINT BSFK_PRAISE_TRANSACTOR FOREIGN KEY (TRANSACTOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ## 营运违章
-- 删除接案人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS DROP CONSTRAINT BSFK_INFRACTB_RECEIVER;
-- 新增接案人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增经办人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_TRANSACTOR FOREIGN KEY (TRANSACTOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增分公司负责人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_BRANCH_CHARGER FOREIGN KEY (BRANCH_CHARGER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增公司审批人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_COMPANY_APPROVAL FOREIGN KEY (COMPANY_APPROVAL_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);


-- ## 投诉
-- 新增经办人外键
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_TRANSACTOR FOREIGN KEY (TRANSACTOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增分公司负责人外键
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_BRANCH_CHARGER FOREIGN KEY (BRANCH_CHARGER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增公司审批人外键
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_COMPANY_APPROVAL FOREIGN KEY (COMPANY_APPROVAL_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增核准人外键
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_HANDLER FOREIGN KEY (HANDLER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);


