-- ###########################################################################
-- 宝城综合应用系统的升级脚本
-- 数据库类型: postgresql
-- 升级版本: 从 0.9 升级到 1.0
-- ###########################################################################


-- ## 营运事件基表
-- 删除结案人外键
ALTER TABLE BS_CASE_BASE DROP CONSTRAINT BSFK_CASEBASE_CLOSER;
-- 新增结案人外键
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_CLOSER FOREIGN KEY (CLOSER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ## 表扬
-- 删除经办人外键
ALTER TABLE BS_CASE_PRAISE DROP CONSTRAINT BSFK_PRAISE_RECEIVER;

-- 经办人更名 --
ALTER TABLE BS_CASE_PRAISE DROP COLUMN RECEIVER_ID;
ALTER TABLE BS_CASE_PRAISE DROP COLUMN RECEIVER_NAME;

-- 经办人 --
ALTER TABLE BS_CASE_PRAISE ADD COLUMN TRANSACTOR_ID INTEGER;
COMMENT ON COLUMN BS_CASE_ADVICE.TRANSACTOR_ID IS '经办人id';
ALTER TABLE BS_CASE_PRAISE ADD COLUMN TRANSACTOR_NAME VARCHAR(255);
COMMENT ON COLUMN BS_CASE_ADVICE.TRANSACTOR_NAME IS '经办人姓名';

-- 新增经办人外键
ALTER TABLE BS_CASE_PRAISE ADD CONSTRAINT BSFK_PRAISE_TRANSACTOR FOREIGN KEY (TRANSACTOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ## 营运违章
-- 删除接案人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS DROP CONSTRAINT BSFK_INFRACTB_RECEIVER;
-- 新增接案人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增经办人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_TRANSACTOR FOREIGN KEY (TRANSACTOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增分公司负责人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_BRANCH_CHARGER FOREIGN KEY (BRANCH_CHARGER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增公司审批人外键
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_COMPANY_APPROVAL FOREIGN KEY (COMPANY_APPROVAL_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);


-- ## 投诉
-- 新增经办人外键
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_TRANSACTOR FOREIGN KEY (TRANSACTOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增分公司负责人外键
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_BRANCH_CHARGER FOREIGN KEY (BRANCH_CHARGER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增公司审批人外键
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_COMPANY_APPROVAL FOREIGN KEY (COMPANY_APPROVAL_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 新增核准人外键
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_HANDLER FOREIGN KEY (HANDLER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ## 事故理赔
-- 删除经办人外键
ALTER TABLE BS_CASE_ACCIDENT DROP CONSTRAINT BSFK_ACCIDENT_CHARGER;

-- 新增经办人外键
ALTER TABLE BS_CASE_ACCIDENT ADD CONSTRAINT BSFK_ACCIDENT_CHARGER FOREIGN KEY (CHARGER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 删除负责人外键
ALTER TABLE BS_CASE_ACCIDENT DROP CONSTRAINT BSFK_ACCIDENT_RECEIVER;

-- 新增负责人外键
ALTER TABLE BS_CASE_ACCIDENT ADD CONSTRAINT BSFK_ACCIDENT_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);


-- ##籍贯表
-- #### 资源配置 ####
insert into BC_IDENTITY_RESOURCE (ID,STATUS_,INNER_,TYPE_,BELONG,ORDER_,NAME,URL,ICONCLASS) 
    select NEXTVAL('CORE_SEQUENCE'), 0, false, 1, m.id, '800400','常用功能', null, 'i0004' from BC_IDENTITY_RESOURCE m where m.order_='800000';
insert into BC_IDENTITY_RESOURCE (ID,STATUS_,INNER_,TYPE_,BELONG,ORDER_,NAME,URL,ICONCLASS,PNAME) 
	select NEXTVAL('CORE_SEQUENCE'), 0, false, 2, m.id, '800401','籍贯管理', '/bc/placeOrigins/paging', 'i0304','常用功能' from BC_IDENTITY_RESOURCE m where m.order_='800400';

-- #### 角色配置 ####
insert into  BC_IDENTITY_ROLE (ID, STATUS_,INNER_,TYPE_,ORDER_,CODE,NAME) 
	values(NEXTVAL('CORE_SEQUENCE'), 0, false,  0,'0006', 'BC_PLACEORIGIN','籍贯管理');

-- #### 权限配置 ####
-- 超级管理员
insert into BC_IDENTITY_ROLE_RESOURCE (RID,SID) 
	select r.id,m.id from BC_IDENTITY_ROLE r,BC_IDENTITY_RESOURCE m where r.code='BC_ADMIN' 
	and m.type_ > 1 and m.order_ in ('800401')
	order by m.order_;

-- 籍贯管理员
insert into BC_IDENTITY_ROLE_RESOURCE (RID,SID) 
	select r.id,m.id from BC_IDENTITY_ROLE r,BC_IDENTITY_RESOURCE m where r.code='BC_PLACEORIGIN' 
	and m.type_ > 1 and m.order_ in ('800401')
	order by m.order_;

-- LPG配置表
-- #### 资源配置 ####
insert into BC_IDENTITY_RESOURCE (ID,STATUS_,INNER_,TYPE_,BELONG,ORDER_,NAME,URL,ICONCLASS,PNAME)
	select NEXTVAL('CORE_SEQUENCE'), 0, false, 2, m.id, '030206','LPG配置', '/bc-business/carLPGs/paging', 'i0007','营运系统/车辆管理' from  BC_IDENTITY_RESOURCE m where m.order_='030200';

-- #### 权限配置 ####
-- 超级管理员
insert into BC_IDENTITY_ROLE_RESOURCE (RID,SID) 
	select r.id,m.id from BC_IDENTITY_ROLE r,BC_IDENTITY_RESOURCE m where r.code='BC_ADMIN' 
	and m.type_ > 1 and m.order_ in ('030206')
	order by m.order_;

-- 车辆管理员
insert into BC_IDENTITY_ROLE_RESOURCE (RID,SID) 
	select r.id,m.id from BC_IDENTITY_ROLE r,BC_IDENTITY_RESOURCE m where r.code='BS_CAR' 
	and m.type_ > 1 and m.order_ in ('030206')
	order by m.order_;

-- #### 插入数据 ####
insert into BS_CAR_LPGMODEL(ID,STATUS_,ORDER_,NAME_,FULL_NAME,MODEL,GP_MODEL,JCF_MODEL,QHQ_MODEL,PSQ_MODEL,FILE_DATE,AUTHOR_ID)
     select NEXTVAL('CORE_SEQUENCE'),0,'01','兰天达','北京兰天达','MPSI（LPG）-LTD-2','鞍山新澳CYSW314-60-2.2','上海星地CYFJ315-30','意大利BRC,FULAIN','Valtck'
				,now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员');
insert into BS_CAR_LPGMODEL(ID,STATUS_,ORDER_,NAME_,FULL_NAME,MODEL,GP_MODEL,JCF_MODEL,QHQ_MODEL,PSQ_MODEL,FILE_DATE,AUTHOR_ID)
     select NEXTVAL('CORE_SEQUENCE'),0,'02','科罗特KRT-1','广州科罗特汽车服务有限公司','KRT-1','CYSW314-60-2.2','科罗特CYFJ','科罗特ZTG-1','科罗特CYFZ'
				,now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员');
