-- ###########################################################################
-- 宝城综合应用系统的升级脚本
-- 数据库类型: postgresql
-- 升级版本: 从 1.4.3升级到 1.4.4
-- ###########################################################################

-- 流程资源配置表type_列的数据类型更改
ALTER TABLE bc_wf_deploy_resource DROP COLUMN type_;
ALTER TABLE bc_wf_deploy_resource DROP COLUMN desc_;
ALTER TABLE bc_wf_deploy_resource ADD COLUMN TYPE_ID INTEGER NOT NULL;
ALTER TABLE bc_wf_deploy_resource ADD COLUMN FORMATTED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bc_wf_deploy_resource ADD CONSTRAINT BCFK_TEMPLATE_TYPE_ID FOREIGN KEY (TYPE_ID)
      REFERENCES BC_TEMPLATE_TYPE (ID);


-- 流程资源使用参数表
drop table if exists BC_WF_DEPLOY_RESOURCE_PARAM;
CREATE TABLE BC_WF_DEPLOY_RESOURCE_PARAM(
		RID INTEGER NOT NULL,
		PID INTEGER NOT NULL,
	CONSTRAINT BCPK_DEPLOY_RESOURCE_PARAM PRIMARY KEY (RID,PID)
);
COMMENT ON TABLE BC_WF_DEPLOY_RESOURCE_PARAM IS '流程资源使用参数表';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE_PARAM.RID IS '流程资源id';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE_PARAM.PID IS '模板参数id';
ALTER TABLE BC_WF_DEPLOY_RESOURCE_PARAM ADD CONSTRAINT BCFK_DEPLOY_RESOURCE FOREIGN KEY (RID)
      REFERENCES BC_WF_DEPLOY_RESOURCE (ID);
ALTER TABLE BC_WF_DEPLOY_RESOURCE_PARAM ADD CONSTRAINT BCFK_TEMPLATE_PARAM FOREIGN KEY (PID)
      REFERENCES BC_TEMPLATE_PARAM(ID);

-- 新增模板类型
INSERT INTO BC_TEMPLATE_TYPE (ID,STATUS_,ORDER_,CODE,NAME,IS_PURE_TEXT,IS_PATH,EXT,FILE_DATE,AUTHOR_ID)
			VALUES (NEXTVAL('CORE_SEQUENCE'),0,'3001','js','JavaScript文件',false,true,'js',now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员'));
INSERT INTO BC_TEMPLATE_TYPE (ID,STATUS_,ORDER_,CODE,NAME,IS_PURE_TEXT,IS_PATH,EXT,FILE_DATE,AUTHOR_ID)
			VALUES (NEXTVAL('CORE_SEQUENCE'),0,'3002','css','Css文件',false,true,'css',now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员'));
INSERT INTO BC_TEMPLATE_TYPE (ID,STATUS_,ORDER_,CODE,NAME,IS_PURE_TEXT,IS_PATH,EXT,FILE_DATE,AUTHOR_ID)
			VALUES (NEXTVAL('CORE_SEQUENCE'),0,'3003','form','Form流程表单文件',false,true,'form',now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员'));
INSERT INTO BC_TEMPLATE_TYPE (ID,STATUS_,ORDER_,CODE,NAME,IS_PURE_TEXT,IS_PATH,EXT,FILE_DATE,AUTHOR_ID)
			VALUES (NEXTVAL('CORE_SEQUENCE'),0,'3004','png','PNG格式图片',false,true,'png',now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员'));

-- 流程附件使用参数表
drop table if exists BC_WF_ATTACH_PARAM;
CREATE TABLE BC_WF_ATTACH_PARAM(
		AID INTEGER NOT NULL,
		PID INTEGER NOT NULL,
	CONSTRAINT BCPK_ATTACH_PARAM PRIMARY KEY (AID,PID)
);
COMMENT ON TABLE BC_WF_ATTACH_PARAM IS '流程附件使用参数表';
COMMENT ON COLUMN BC_WF_ATTACH_PARAM.AID IS '流程附件id';
COMMENT ON COLUMN BC_WF_ATTACH_PARAM.PID IS '模板参数id';
ALTER TABLE BC_WF_ATTACH_PARAM ADD CONSTRAINT BCFK_ATTACH_RESOURCE FOREIGN KEY (AID)
      REFERENCES BC_WF_ATTACH (ID);
ALTER TABLE BC_WF_ATTACH_PARAM ADD CONSTRAINT BCFK_TEMPLATE_PARAM FOREIGN KEY (PID)
      REFERENCES BC_TEMPLATE_PARAM(ID);

--更新流程附件使用参数表数据
insert into bc_wf_attach_param
 select a.id,ttp.pid from bc_wf_attach a
 inner join bc_template t on a.template_id = t.id 
 inner join bc_template_template_param ttp on ttp.tid = t.id 


--删除流程附件的模板id
ALTER TABLE BC_WF_ATTACHDROP COLUMN TEMPLATE_ID;