-- ###########################################################################
-- 宝城综合应用系统的升级脚本
-- 数据库类型: postgresql
-- 升级版本: 从 1.4.2升级到 1.4.3
-- ###########################################################################

-- 增加发票退票人字段
ALTER TABLE BS_INVOICE_SELL ADD COLUMN REFUNDER_ID INTEGER;
COMMENT ON COLUMN BS_INVOICE_SELL.REFUNDER_ID IS '退票人ID';

ALTER TABLE BS_INVOICE_SELL ADD CONSTRAINT BSFK_INVOICESELL_REFUNDER FOREIGN KEY (REFUNDER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 修改粤A.MG461发票退票单退票人为黄剑华
update bs_invoice_sell SET refunder_id = (select a.id
FROM bc_identity_actor_history a
where a.actor_code='foy') 
where status_=0 and type_=2 and car_plate='粤A.MG461';
	  

--车辆信息模块表添加管理号
ALTER TABLE BS_CAR ADD COLUMN MANAGE_NO INTEGER;
COMMENT ON COLUMN BS_CAR.MANAGE_NO IS '管理号:由4位数字组成，前两位代表车辆所属的车队，如11代表一分一队，后两位为流水号，从01开始';



-- 流程资源配置表type_列的数据类型更改
ALTER TABLE bc_wf_deploy_resource DROP COLUMN type_;
ALTER TABLE bc_wf_deploy_resource DROP COLUMN desc_;
ALTER TABLE bc_wf_deploy_resource ADD COLUMN TYPE_ID INTEGER NOT NULL;
ALTER TABLE bc_wf_deploy_resource ADD COLUMN FORMATTED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bc_wf_deploy_resource ADD CONSTRAINT BCFK_TEMPLATE_TYPE_ID FOREIGN KEY (TYPE_ID)
      REFERENCES BC_TEMPLATE_TYPE (ID);


-- 流程资源使用参数表
drop table if exists BC_WF_DEPLOY_RESOURCE_PARAM;
CREATE TABLE BC_WF_DEPLOY_RESOURCE_PARAM(
		RID INTEGER NOT NULL,
		PID INTEGER NOT NULL,
	CONSTRAINT BCPK_DEPLOY_RESOURCE_PARAM PRIMARY KEY (RID,PID)
);
COMMENT ON TABLE BC_WF_DEPLOY_RESOURCE_PARAM IS '流程资源使用参数表';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE_PARAM.RID IS '流程资源id';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE_PARAM.PID IS '模板参数id';
ALTER TABLE BC_WF_DEPLOY_RESOURCE_PARAM ADD CONSTRAINT BCFK_DEPLOY_RESOURCE FOREIGN KEY (RID)
      REFERENCES BC_WF_DEPLOY_RESOURCE (ID);
ALTER TABLE BC_WF_DEPLOY_RESOURCE_PARAM ADD CONSTRAINT BCFK_TEMPLATE_PARAM FOREIGN KEY (PID)
      REFERENCES BC_TEMPLATE_PARAM(ID);

-- 新增模板类型
INSERT INTO BC_TEMPLATE_TYPE (ID,STATUS_,ORDER_,CODE,NAME,IS_PURE_TEXT,IS_PATH,EXT,FILE_DATE,AUTHOR_ID)
			VALUES (NEXTVAL('CORE_SEQUENCE'),0,'3001','js','JavaScript文件',false,true,'js',now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员'));
INSERT INTO BC_TEMPLATE_TYPE (ID,STATUS_,ORDER_,CODE,NAME,IS_PURE_TEXT,IS_PATH,EXT,FILE_DATE,AUTHOR_ID)
			VALUES (NEXTVAL('CORE_SEQUENCE'),0,'3002','css','Css文件',false,true,'css',now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员'));
INSERT INTO BC_TEMPLATE_TYPE (ID,STATUS_,ORDER_,CODE,NAME,IS_PURE_TEXT,IS_PATH,EXT,FILE_DATE,AUTHOR_ID)
			VALUES (NEXTVAL('CORE_SEQUENCE'),0,'3003','form','Form流程表单文件',false,true,'form',now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员'));
INSERT INTO BC_TEMPLATE_TYPE (ID,STATUS_,ORDER_,CODE,NAME,IS_PURE_TEXT,IS_PATH,EXT,FILE_DATE,AUTHOR_ID)
			VALUES (NEXTVAL('CORE_SEQUENCE'),0,'3004','png','PNG格式图片',false,true,'png',now(),(select id from BC_IDENTITY_ACTOR_HISTORY where actor_name='系统管理员'));

-- 流程附件使用参数表
drop table if exists BC_WF_ATTACH_PARAM;
CREATE TABLE BC_WF_ATTACH_PARAM(
		AID INTEGER NOT NULL,
		PID INTEGER NOT NULL,
	CONSTRAINT BCPK_ATTACH_PARAM PRIMARY KEY (AID,PID)
);
COMMENT ON TABLE BC_WF_ATTACH_PARAM IS '流程附件使用参数表';
COMMENT ON COLUMN BC_WF_ATTACH_PARAM.AID IS '流程附件id';
COMMENT ON COLUMN BC_WF_ATTACH_PARAM.PID IS '模板参数id';
ALTER TABLE BC_WF_ATTACH_PARAM ADD CONSTRAINT BCFK_ATTACH_RESOURCE FOREIGN KEY (AID)
      REFERENCES BC_WF_ATTACH (ID);
ALTER TABLE BC_WF_ATTACH_PARAM ADD CONSTRAINT BCFK_TEMPLATE_PARAM FOREIGN KEY (PID)
      REFERENCES BC_TEMPLATE_PARAM(ID);

--更新流程附件使用参数表数据
insert into bc_wf_attach_param
 select a.id,ttp.pid from bc_wf_attach a
 inner join bc_template t on a.template_id = t.id 
 inner join bc_template_template_param ttp on ttp.tid = t.id 


--删除流程附件的模板id
ALTER TABLE BC_WF_ATTACHDROP COLUMN TEMPLATE_ID;