-- ###########################################################################
-- 宝城综合应用系统的升级脚本
-- 数据库类型: postgresql
-- 升级版本: 从 1.4.1升级到 1.4.2
-- ###########################################################################

-- 流程资源配置表
drop table if exists BC_WF_DEPLOY_RESOURCE;

CREATE TABLE BC_WF_DEPLOY_RESOURCE (
	ID	INTEGER	NOT NULL,
	UID_	VARCHAR(36) NOT NULL,
	PID	INTEGER	NOT NULL,
	TYPE_	INTEGER	NOT NULL DEFAULT 0,
	CODE	VARCHAR(255)	NOT NULL,
	SUBJECT	VARCHAR(255)	NOT NULL,
	PATH	VARCHAR(255)	NOT NULL,
	SIZE_	INTEGER	NOT NULL DEFAULT 0,
	SOURCE	VARCHAR(255)	NOT NULL,
	DESC_	VARCHAR(4000),
CONSTRAINT BSPK_WF_DEPLOY_RESOURCE PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_WF_DEPLOY_RESOURCE IS '流程资源配置表';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE.PID IS '流程部署ID';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE.TYPE_ IS '资源类型';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE.CODE IS '编码';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE.SUBJECT IS '名称';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE.PATH IS '路径';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE.SIZE_ IS '文件大小';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE.SOURCE IS '原文件名';
COMMENT ON COLUMN BC_WF_DEPLOY_RESOURCE.DESC_ IS '备注';
ALTER TABLE BC_WF_DEPLOY_RESOURCE ADD CONSTRAINT BSFK_WF_DEPLOY FOREIGN KEY (PID)
      REFERENCES BC_WF_DEPLOY (ID);